package gov.usgs.ngwmn.dm.dao;

import java.math.BigDecimal;
import java.util.Date;

public class CacheMetaData extends CacheMetaDataKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.CACHE_META_DATA.SUCCESS_CT
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private Integer successCt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.CACHE_META_DATA.FAIL_CT
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private Integer failCt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.CACHE_META_DATA.FIRST_DATA_DT
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private Date firstDataDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.CACHE_META_DATA.LAST_DATA_DT
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private Date lastDataDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.CACHE_META_DATA.MOST_RECENT_FETCH_DT
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private Date mostRecentFetchDt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.CACHE_META_DATA.SUCCESS_CT
	 * @return  the value of GW_DATA_PORTAL.CACHE_META_DATA.SUCCESS_CT
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public Integer getSuccessCt() {
		return successCt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.CACHE_META_DATA.SUCCESS_CT
	 * @param successCt  the value for GW_DATA_PORTAL.CACHE_META_DATA.SUCCESS_CT
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public void setSuccessCt(Integer successCt) {
		this.successCt = successCt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.CACHE_META_DATA.FAIL_CT
	 * @return  the value of GW_DATA_PORTAL.CACHE_META_DATA.FAIL_CT
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public Integer getFailCt() {
		return failCt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.CACHE_META_DATA.FAIL_CT
	 * @param failCt  the value for GW_DATA_PORTAL.CACHE_META_DATA.FAIL_CT
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public void setFailCt(Integer failCt) {
		this.failCt = failCt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.CACHE_META_DATA.FIRST_DATA_DT
	 * @return  the value of GW_DATA_PORTAL.CACHE_META_DATA.FIRST_DATA_DT
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public Date getFirstDataDt() {
		return firstDataDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.CACHE_META_DATA.FIRST_DATA_DT
	 * @param firstDataDt  the value for GW_DATA_PORTAL.CACHE_META_DATA.FIRST_DATA_DT
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public void setFirstDataDt(Date firstDataDt) {
		this.firstDataDt = firstDataDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.CACHE_META_DATA.LAST_DATA_DT
	 * @return  the value of GW_DATA_PORTAL.CACHE_META_DATA.LAST_DATA_DT
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public Date getLastDataDt() {
		return lastDataDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.CACHE_META_DATA.LAST_DATA_DT
	 * @param lastDataDt  the value for GW_DATA_PORTAL.CACHE_META_DATA.LAST_DATA_DT
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public void setLastDataDt(Date lastDataDt) {
		this.lastDataDt = lastDataDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.CACHE_META_DATA.MOST_RECENT_FETCH_DT
	 * @return  the value of GW_DATA_PORTAL.CACHE_META_DATA.MOST_RECENT_FETCH_DT
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public Date getMostRecentFetchDt() {
		return mostRecentFetchDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.CACHE_META_DATA.MOST_RECENT_FETCH_DT
	 * @param mostRecentFetchDt  the value for GW_DATA_PORTAL.CACHE_META_DATA.MOST_RECENT_FETCH_DT
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public void setMostRecentFetchDt(Date mostRecentFetchDt) {
		this.mostRecentFetchDt = mostRecentFetchDt;
	}
}