package gov.usgs.ngwmn.dm.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import gov.usgs.ngwmn.dm.dao.CacheMetaData;
import gov.usgs.ngwmn.dm.dao.CacheMetaDataExample;
import gov.usgs.ngwmn.dm.dao.CacheMetaDataKey;

public interface CacheMetaDataMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.CACHE_META_DATA
	 * @mbggenerated  Tue Jun 19 12:15:56 CDT 2012
	 */
	int countByExample(CacheMetaDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.CACHE_META_DATA
	 * @mbggenerated  Tue Jun 19 12:15:56 CDT 2012
	 */
	int deleteByExample(CacheMetaDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.CACHE_META_DATA
	 * @mbggenerated  Tue Jun 19 12:15:56 CDT 2012
	 */
	@Delete({ "delete from GW_DATA_PORTAL.CACHE_META_DATA",
			"where AGENCY_CD = #{agencyCd,jdbcType=VARCHAR}",
			"and DATA_TYPE = #{dataType,jdbcType=VARCHAR}",
			"and SITE_NO = #{siteNo,jdbcType=VARCHAR}" })
	int deleteByPrimaryKey(CacheMetaDataKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.CACHE_META_DATA
	 * @mbggenerated  Tue Jun 19 12:15:56 CDT 2012
	 */
	@Insert({
			"insert into GW_DATA_PORTAL.CACHE_META_DATA (AGENCY_CD, DATA_TYPE, ",
			"SITE_NO, SUCCESS_CT, ",
			"FAIL_CT, FIRST_DATA_DT, ",
			"LAST_DATA_DT, MOST_RECENT_SUCCESS_DT, ",
			"MOST_RECENT_ATTEMPT_DT, MOST_RECENT_FAIL_DT, ",
			"FETCH_PRIORITY, EMPTY_CT, ",
			"MOST_RECENT_EMPTY_DT)",
			"values (#{agencyCd,jdbcType=VARCHAR}, #{dataType,jdbcType=VARCHAR}, ",
			"#{siteNo,jdbcType=VARCHAR}, #{successCt,jdbcType=DECIMAL}, ",
			"#{failCt,jdbcType=DECIMAL}, #{firstDataDt,jdbcType=TIMESTAMP}, ",
			"#{lastDataDt,jdbcType=TIMESTAMP}, #{mostRecentSuccessDt,jdbcType=TIMESTAMP}, ",
			"#{mostRecentAttemptDt,jdbcType=TIMESTAMP}, #{mostRecentFailDt,jdbcType=TIMESTAMP}, ",
			"#{fetchPriority,jdbcType=DECIMAL}, #{emptyCt,jdbcType=DECIMAL}, ",
			"#{mostRecentEmptyDt,jdbcType=TIMESTAMP})" })
	int insert(CacheMetaData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.CACHE_META_DATA
	 * @mbggenerated  Tue Jun 19 12:15:56 CDT 2012
	 */
	int insertSelective(CacheMetaData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.CACHE_META_DATA
	 * @mbggenerated  Tue Jun 19 12:15:56 CDT 2012
	 */
	List<CacheMetaData> selectByExample(CacheMetaDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.CACHE_META_DATA
	 * @mbggenerated  Tue Jun 19 12:15:56 CDT 2012
	 */
	@Select({
			"select",
			"AGENCY_CD, DATA_TYPE, SITE_NO, SUCCESS_CT, FAIL_CT, FIRST_DATA_DT, LAST_DATA_DT, ",
			"MOST_RECENT_SUCCESS_DT, MOST_RECENT_ATTEMPT_DT, MOST_RECENT_FAIL_DT, FETCH_PRIORITY, ",
			"EMPTY_CT, MOST_RECENT_EMPTY_DT",
			"from GW_DATA_PORTAL.CACHE_META_DATA",
			"where AGENCY_CD = #{agencyCd,jdbcType=VARCHAR}",
			"and DATA_TYPE = #{dataType,jdbcType=VARCHAR}",
			"and SITE_NO = #{siteNo,jdbcType=VARCHAR}" })
	@ResultMap("BaseResultMap")
	CacheMetaData selectByPrimaryKey(CacheMetaDataKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.CACHE_META_DATA
	 * @mbggenerated  Tue Jun 19 12:15:56 CDT 2012
	 */
	int updateByExampleSelective(@Param("record") CacheMetaData record,
			@Param("example") CacheMetaDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.CACHE_META_DATA
	 * @mbggenerated  Tue Jun 19 12:15:56 CDT 2012
	 */
	int updateByExample(@Param("record") CacheMetaData record,
			@Param("example") CacheMetaDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.CACHE_META_DATA
	 * @mbggenerated  Tue Jun 19 12:15:56 CDT 2012
	 */
	int updateByPrimaryKeySelective(CacheMetaData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.CACHE_META_DATA
	 * @mbggenerated  Tue Jun 19 12:15:56 CDT 2012
	 */
	@Update({
			"update GW_DATA_PORTAL.CACHE_META_DATA",
			"set SUCCESS_CT = #{successCt,jdbcType=DECIMAL},",
			"FAIL_CT = #{failCt,jdbcType=DECIMAL},",
			"FIRST_DATA_DT = #{firstDataDt,jdbcType=TIMESTAMP},",
			"LAST_DATA_DT = #{lastDataDt,jdbcType=TIMESTAMP},",
			"MOST_RECENT_SUCCESS_DT = #{mostRecentSuccessDt,jdbcType=TIMESTAMP},",
			"MOST_RECENT_ATTEMPT_DT = #{mostRecentAttemptDt,jdbcType=TIMESTAMP},",
			"MOST_RECENT_FAIL_DT = #{mostRecentFailDt,jdbcType=TIMESTAMP},",
			"FETCH_PRIORITY = #{fetchPriority,jdbcType=DECIMAL},",
			"EMPTY_CT = #{emptyCt,jdbcType=DECIMAL},",
			"MOST_RECENT_EMPTY_DT = #{mostRecentEmptyDt,jdbcType=TIMESTAMP}",
			"where AGENCY_CD = #{agencyCd,jdbcType=VARCHAR}",
			"and DATA_TYPE = #{dataType,jdbcType=VARCHAR}",
			"and SITE_NO = #{siteNo,jdbcType=VARCHAR}" })
	int updateByPrimaryKey(CacheMetaData record);

	@Select({
		"select",
		"AGENCY_CD, DATA_TYPE, SITE_NO, SUCCESS_CT, FAIL_CT, FIRST_DATA_DT, LAST_DATA_DT, ",
		"MOST_RECENT_SUCCESS_DT, MOST_RECENT_ATTEMPT_DT, MOST_RECENT_FAIL_DT, FETCH_PRIORITY, ",
		"EMPTY_CT, MOST_RECENT_EMPTY_DT",
		"from GW_DATA_PORTAL.CACHE_META_DATA",
		"where AGENCY_CD = #{agencyCd,jdbcType=VARCHAR}",
		"order by AGENCY_CD, SITE_NO, DATA_TYPE"
	})
	@ResultMap("BaseResultMap")
	List<CacheMetaData> listByAgencyCd(String agencyCd);

	@Select({
		"select",
		"AGENCY_CD, DATA_TYPE, SITE_NO, SUCCESS_CT, FAIL_CT, FIRST_DATA_DT, LAST_DATA_DT, ",
		"MOST_RECENT_SUCCESS_DT, MOST_RECENT_ATTEMPT_DT, MOST_RECENT_FAIL_DT, FETCH_PRIORITY",
		"EMPTY_CT, MOST_RECENT_EMPTY_DT",
		"from GW_DATA_PORTAL.CACHE_META_DATA",
		"WHERE SUCCESS_CT > 0 OR FAIL_CT > 0 ",
		"order by AGENCY_CD, SITE_NO, DATA_TYPE"
	})
	@ResultMap("BaseResultMap")
	List<CacheMetaData> listAll();
	
	@Select({
		"select",
		"AGENCY_CD, DATA_TYPE, SITE_NO, SUCCESS_CT, FAIL_CT, FIRST_DATA_DT, LAST_DATA_DT, ",
		"MOST_RECENT_SUCCESS_DT, MOST_RECENT_ATTEMPT_DT, MOST_RECENT_FAIL_DT, FETCH_PRIORITY",
		"EMPTY_CT, MOST_RECENT_EMPTY_DT",
		"from GW_DATA_PORTAL.CACHE_META_DATA",
		"WHERE SUCCESS_CT > 0 OR FAIL_CT > 0 ",
		"order by MOST_RECENT_ATTEMPT_DT DESC, AGENCY_CD, SITE_NO, DATA_TYPE"
	})
	@ResultMap("BaseResultMap")
	List<CacheMetaData> listAllByFetchDate();
	
	@Select({
		"select ",
		"agency_cd, ' ' as DATA_TYPE, ' ' as SITE_NO, SUM(SUCCESS_CT) as SUCCESS_CT, SUM(FAIL_CT) as FAIL_CT, MAX(FIRST_DATA_DT) as FIRST_DATA_DT, MAX(LAST_DATA_DT) as LAST_DATA_DT, ",
		"MAX(MOST_RECENT_SUCCESS_DT) as MOST_RECENT_SUCCESS_DT, MAX(MOST_RECENT_ATTEMPT_DT) as MOST_RECENT_ATTEMPT_DT, MAX(MOST_RECENT_FAIL_DT) as MOST_RECENT_FAIL_DT, MAX(FETCH_PRIORITY) as FETCH_PRIORITY,",
		"SUM(EMPTY_CT) as EMPTY_CT, MAX(MOST_RECENT_EMPTY_DT) as MOST_RECENT_EMPTY_DT",
		"from GW_DATA_PORTAL.CACHE_META_DATA",
		"group by agency_cd"
	})
	@ResultMap("BaseResultMap")
	List<CacheMetaData> listAgencySummary();
	

	void updateCacheMetaData();

	
}