package gov.usgs.ngwmn.dm.dao;

public class CacheMetaDataKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.CACHE_META_DATA.AGENCY_CD
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String agencyCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.CACHE_META_DATA.DATA_TYPE
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String dataType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.CACHE_META_DATA.SITE_NO
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String siteNo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.CACHE_META_DATA.AGENCY_CD
	 * @return  the value of GW_DATA_PORTAL.CACHE_META_DATA.AGENCY_CD
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getAgencyCd() {
		return agencyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.CACHE_META_DATA.AGENCY_CD
	 * @param agencyCd  the value for GW_DATA_PORTAL.CACHE_META_DATA.AGENCY_CD
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public void setAgencyCd(String agencyCd) {
		this.agencyCd = agencyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.CACHE_META_DATA.DATA_TYPE
	 * @return  the value of GW_DATA_PORTAL.CACHE_META_DATA.DATA_TYPE
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getDataType() {
		return dataType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.CACHE_META_DATA.DATA_TYPE
	 * @param dataType  the value for GW_DATA_PORTAL.CACHE_META_DATA.DATA_TYPE
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public void setDataType(String dataType) {
		this.dataType = dataType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.CACHE_META_DATA.SITE_NO
	 * @return  the value of GW_DATA_PORTAL.CACHE_META_DATA.SITE_NO
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getSiteNo() {
		return siteNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.CACHE_META_DATA.SITE_NO
	 * @param siteNo  the value for GW_DATA_PORTAL.CACHE_META_DATA.SITE_NO
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public void setSiteNo(String siteNo) {
		this.siteNo = siteNo;
	}
}