package gov.usgs.ngwmn.dm.dao;

import java.util.Date;

public class FetchLog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.FETCH_LOG.FETCHLOG_ID
	 * @mbggenerated  Fri Mar 30 16:21:22 CDT 2012
	 */
	private Integer fetchlogId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.FETCH_LOG.DATA_SOURCE
	 * @mbggenerated  Fri Mar 30 16:21:22 CDT 2012
	 */
	private String source;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.FETCH_LOG.STARTED_AT
	 * @mbggenerated  Fri Mar 30 16:21:22 CDT 2012
	 */
	private Date startedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.FETCH_LOG.STATUS
	 * @mbggenerated  Fri Mar 30 16:21:22 CDT 2012
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.FETCH_LOG.PROBLEM
	 * @mbggenerated  Fri Mar 30 16:21:22 CDT 2012
	 */
	private String problem;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.FETCH_LOG.CT
	 * @mbggenerated  Fri Mar 30 16:21:22 CDT 2012
	 */
	private Integer ct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.FETCH_LOG.ELAPSED_SEC
	 * @mbggenerated  Fri Mar 30 16:21:22 CDT 2012
	 */
	private Double elapsedSec;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.FETCH_LOG.SPECIFIER
	 * @mbggenerated  Fri Mar 30 16:21:22 CDT 2012
	 */
	private String specifier;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.FETCH_LOG.FETCHLOG_ID
	 * @return  the value of GW_DATA_PORTAL.FETCH_LOG.FETCHLOG_ID
	 * @mbggenerated  Fri Mar 30 16:21:22 CDT 2012
	 */
	public Integer getFetchlogId() {
		return fetchlogId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.FETCH_LOG.FETCHLOG_ID
	 * @param fetchlogId  the value for GW_DATA_PORTAL.FETCH_LOG.FETCHLOG_ID
	 * @mbggenerated  Fri Mar 30 16:21:22 CDT 2012
	 */
	public void setFetchlogId(Integer fetchlogId) {
		this.fetchlogId = fetchlogId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.FETCH_LOG.DATA_SOURCE
	 * @return  the value of GW_DATA_PORTAL.FETCH_LOG.DATA_SOURCE
	 * @mbggenerated  Fri Mar 30 16:21:22 CDT 2012
	 */
	public String getSource() {
		return source;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.FETCH_LOG.DATA_SOURCE
	 * @param source  the value for GW_DATA_PORTAL.FETCH_LOG.DATA_SOURCE
	 * @mbggenerated  Fri Mar 30 16:21:22 CDT 2012
	 */
	public void setSource(String source) {
		this.source = source;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.FETCH_LOG.STARTED_AT
	 * @return  the value of GW_DATA_PORTAL.FETCH_LOG.STARTED_AT
	 * @mbggenerated  Fri Mar 30 16:21:22 CDT 2012
	 */
	public Date getStartedAt() {
		return startedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.FETCH_LOG.STARTED_AT
	 * @param startedAt  the value for GW_DATA_PORTAL.FETCH_LOG.STARTED_AT
	 * @mbggenerated  Fri Mar 30 16:21:22 CDT 2012
	 */
	public void setStartedAt(Date startedAt) {
		this.startedAt = startedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.FETCH_LOG.STATUS
	 * @return  the value of GW_DATA_PORTAL.FETCH_LOG.STATUS
	 * @mbggenerated  Fri Mar 30 16:21:22 CDT 2012
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.FETCH_LOG.STATUS
	 * @param status  the value for GW_DATA_PORTAL.FETCH_LOG.STATUS
	 * @mbggenerated  Fri Mar 30 16:21:22 CDT 2012
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.FETCH_LOG.PROBLEM
	 * @return  the value of GW_DATA_PORTAL.FETCH_LOG.PROBLEM
	 * @mbggenerated  Fri Mar 30 16:21:22 CDT 2012
	 */
	public String getProblem() {
		return problem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.FETCH_LOG.PROBLEM
	 * @param problem  the value for GW_DATA_PORTAL.FETCH_LOG.PROBLEM
	 * @mbggenerated  Fri Mar 30 16:21:22 CDT 2012
	 */
	public void setProblem(String problem) {
		this.problem = problem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.FETCH_LOG.CT
	 * @return  the value of GW_DATA_PORTAL.FETCH_LOG.CT
	 * @mbggenerated  Fri Mar 30 16:21:22 CDT 2012
	 */
	public Integer getCt() {
		return ct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.FETCH_LOG.CT
	 * @param ct  the value for GW_DATA_PORTAL.FETCH_LOG.CT
	 * @mbggenerated  Fri Mar 30 16:21:22 CDT 2012
	 */
	public void setCt(Integer ct) {
		this.ct = ct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.FETCH_LOG.ELAPSED_SEC
	 * @return  the value of GW_DATA_PORTAL.FETCH_LOG.ELAPSED_SEC
	 * @mbggenerated  Fri Mar 30 16:21:22 CDT 2012
	 */
	public Double getElapsedSec() {
		return elapsedSec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.FETCH_LOG.ELAPSED_SEC
	 * @param elapsedSec  the value for GW_DATA_PORTAL.FETCH_LOG.ELAPSED_SEC
	 * @mbggenerated  Fri Mar 30 16:21:22 CDT 2012
	 */
	public void setElapsedSec(Double elapsedSec) {
		this.elapsedSec = elapsedSec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.FETCH_LOG.SPECIFIER
	 * @return  the value of GW_DATA_PORTAL.FETCH_LOG.SPECIFIER
	 * @mbggenerated  Fri Mar 30 16:21:22 CDT 2012
	 */
	public String getSpecifier() {
		return specifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.FETCH_LOG.SPECIFIER
	 * @param specifier  the value for GW_DATA_PORTAL.FETCH_LOG.SPECIFIER
	 * @mbggenerated  Fri Mar 30 16:21:22 CDT 2012
	 */
	public void setSpecifier(String specifier) {
		this.specifier = specifier;
	}
}