package gov.usgs.ngwmn.dm.dao;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FetchLogExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table GW_DATA_PORTAL.FETCH_LOG
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table GW_DATA_PORTAL.FETCH_LOG
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table GW_DATA_PORTAL.FETCH_LOG
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.FETCH_LOG
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public FetchLogExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.FETCH_LOG
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.FETCH_LOG
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.FETCH_LOG
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.FETCH_LOG
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.FETCH_LOG
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.FETCH_LOG
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.FETCH_LOG
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.FETCH_LOG
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.FETCH_LOG
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.FETCH_LOG
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table GW_DATA_PORTAL.FETCH_LOG
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andFetchlogIdIsNull() {
			addCriterion("FETCHLOG_ID is null");
			return (Criteria) this;
		}

		public Criteria andFetchlogIdIsNotNull() {
			addCriterion("FETCHLOG_ID is not null");
			return (Criteria) this;
		}

		public Criteria andFetchlogIdEqualTo(Integer value) {
			addCriterion("FETCHLOG_ID =", value, "fetchlogId");
			return (Criteria) this;
		}

		public Criteria andFetchlogIdNotEqualTo(Integer value) {
			addCriterion("FETCHLOG_ID <>", value, "fetchlogId");
			return (Criteria) this;
		}

		public Criteria andFetchlogIdGreaterThan(Integer value) {
			addCriterion("FETCHLOG_ID >", value, "fetchlogId");
			return (Criteria) this;
		}

		public Criteria andFetchlogIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("FETCHLOG_ID >=", value, "fetchlogId");
			return (Criteria) this;
		}

		public Criteria andFetchlogIdLessThan(Integer value) {
			addCriterion("FETCHLOG_ID <", value, "fetchlogId");
			return (Criteria) this;
		}

		public Criteria andFetchlogIdLessThanOrEqualTo(Integer value) {
			addCriterion("FETCHLOG_ID <=", value, "fetchlogId");
			return (Criteria) this;
		}

		public Criteria andFetchlogIdIn(List<Integer> values) {
			addCriterion("FETCHLOG_ID in", values, "fetchlogId");
			return (Criteria) this;
		}

		public Criteria andFetchlogIdNotIn(List<Integer> values) {
			addCriterion("FETCHLOG_ID not in", values, "fetchlogId");
			return (Criteria) this;
		}

		public Criteria andFetchlogIdBetween(Integer value1, Integer value2) {
			addCriterion("FETCHLOG_ID between", value1, value2, "fetchlogId");
			return (Criteria) this;
		}

		public Criteria andFetchlogIdNotBetween(Integer value1, Integer value2) {
			addCriterion("FETCHLOG_ID not between", value1, value2,
					"fetchlogId");
			return (Criteria) this;
		}

		public Criteria andAgencyCdIsNull() {
			addCriterion("AGENCY_CD is null");
			return (Criteria) this;
		}

		public Criteria andAgencyCdIsNotNull() {
			addCriterion("AGENCY_CD is not null");
			return (Criteria) this;
		}

		public Criteria andAgencyCdEqualTo(String value) {
			addCriterion("AGENCY_CD =", value, "agencyCd");
			return (Criteria) this;
		}

		public Criteria andAgencyCdNotEqualTo(String value) {
			addCriterion("AGENCY_CD <>", value, "agencyCd");
			return (Criteria) this;
		}

		public Criteria andAgencyCdGreaterThan(String value) {
			addCriterion("AGENCY_CD >", value, "agencyCd");
			return (Criteria) this;
		}

		public Criteria andAgencyCdGreaterThanOrEqualTo(String value) {
			addCriterion("AGENCY_CD >=", value, "agencyCd");
			return (Criteria) this;
		}

		public Criteria andAgencyCdLessThan(String value) {
			addCriterion("AGENCY_CD <", value, "agencyCd");
			return (Criteria) this;
		}

		public Criteria andAgencyCdLessThanOrEqualTo(String value) {
			addCriterion("AGENCY_CD <=", value, "agencyCd");
			return (Criteria) this;
		}

		public Criteria andAgencyCdLike(String value) {
			addCriterion("AGENCY_CD like", value, "agencyCd");
			return (Criteria) this;
		}

		public Criteria andAgencyCdNotLike(String value) {
			addCriterion("AGENCY_CD not like", value, "agencyCd");
			return (Criteria) this;
		}

		public Criteria andAgencyCdIn(List<String> values) {
			addCriterion("AGENCY_CD in", values, "agencyCd");
			return (Criteria) this;
		}

		public Criteria andAgencyCdNotIn(List<String> values) {
			addCriterion("AGENCY_CD not in", values, "agencyCd");
			return (Criteria) this;
		}

		public Criteria andAgencyCdBetween(String value1, String value2) {
			addCriterion("AGENCY_CD between", value1, value2, "agencyCd");
			return (Criteria) this;
		}

		public Criteria andAgencyCdNotBetween(String value1, String value2) {
			addCriterion("AGENCY_CD not between", value1, value2, "agencyCd");
			return (Criteria) this;
		}

		public Criteria andSiteNoIsNull() {
			addCriterion("SITE_NO is null");
			return (Criteria) this;
		}

		public Criteria andSiteNoIsNotNull() {
			addCriterion("SITE_NO is not null");
			return (Criteria) this;
		}

		public Criteria andSiteNoEqualTo(String value) {
			addCriterion("SITE_NO =", value, "siteNo");
			return (Criteria) this;
		}

		public Criteria andSiteNoNotEqualTo(String value) {
			addCriterion("SITE_NO <>", value, "siteNo");
			return (Criteria) this;
		}

		public Criteria andSiteNoGreaterThan(String value) {
			addCriterion("SITE_NO >", value, "siteNo");
			return (Criteria) this;
		}

		public Criteria andSiteNoGreaterThanOrEqualTo(String value) {
			addCriterion("SITE_NO >=", value, "siteNo");
			return (Criteria) this;
		}

		public Criteria andSiteNoLessThan(String value) {
			addCriterion("SITE_NO <", value, "siteNo");
			return (Criteria) this;
		}

		public Criteria andSiteNoLessThanOrEqualTo(String value) {
			addCriterion("SITE_NO <=", value, "siteNo");
			return (Criteria) this;
		}

		public Criteria andSiteNoLike(String value) {
			addCriterion("SITE_NO like", value, "siteNo");
			return (Criteria) this;
		}

		public Criteria andSiteNoNotLike(String value) {
			addCriterion("SITE_NO not like", value, "siteNo");
			return (Criteria) this;
		}

		public Criteria andSiteNoIn(List<String> values) {
			addCriterion("SITE_NO in", values, "siteNo");
			return (Criteria) this;
		}

		public Criteria andSiteNoNotIn(List<String> values) {
			addCriterion("SITE_NO not in", values, "siteNo");
			return (Criteria) this;
		}

		public Criteria andSiteNoBetween(String value1, String value2) {
			addCriterion("SITE_NO between", value1, value2, "siteNo");
			return (Criteria) this;
		}

		public Criteria andSiteNoNotBetween(String value1, String value2) {
			addCriterion("SITE_NO not between", value1, value2, "siteNo");
			return (Criteria) this;
		}

		public Criteria andSourceIsNull() {
			addCriterion("DATA_SOURCE is null");
			return (Criteria) this;
		}

		public Criteria andSourceIsNotNull() {
			addCriterion("DATA_SOURCE is not null");
			return (Criteria) this;
		}

		public Criteria andSourceEqualTo(String value) {
			addCriterion("DATA_SOURCE =", value, "source");
			return (Criteria) this;
		}

		public Criteria andSourceNotEqualTo(String value) {
			addCriterion("DATA_SOURCE <>", value, "source");
			return (Criteria) this;
		}

		public Criteria andSourceGreaterThan(String value) {
			addCriterion("DATA_SOURCE >", value, "source");
			return (Criteria) this;
		}

		public Criteria andSourceGreaterThanOrEqualTo(String value) {
			addCriterion("DATA_SOURCE >=", value, "source");
			return (Criteria) this;
		}

		public Criteria andSourceLessThan(String value) {
			addCriterion("DATA_SOURCE <", value, "source");
			return (Criteria) this;
		}

		public Criteria andSourceLessThanOrEqualTo(String value) {
			addCriterion("DATA_SOURCE <=", value, "source");
			return (Criteria) this;
		}

		public Criteria andSourceLike(String value) {
			addCriterion("DATA_SOURCE like", value, "source");
			return (Criteria) this;
		}

		public Criteria andSourceNotLike(String value) {
			addCriterion("DATA_SOURCE not like", value, "source");
			return (Criteria) this;
		}

		public Criteria andSourceIn(List<String> values) {
			addCriterion("DATA_SOURCE in", values, "source");
			return (Criteria) this;
		}

		public Criteria andSourceNotIn(List<String> values) {
			addCriterion("DATA_SOURCE not in", values, "source");
			return (Criteria) this;
		}

		public Criteria andSourceBetween(String value1, String value2) {
			addCriterion("DATA_SOURCE between", value1, value2, "source");
			return (Criteria) this;
		}

		public Criteria andSourceNotBetween(String value1, String value2) {
			addCriterion("DATA_SOURCE not between", value1, value2, "source");
			return (Criteria) this;
		}

		public Criteria andStartedAtIsNull() {
			addCriterion("STARTED_AT is null");
			return (Criteria) this;
		}

		public Criteria andStartedAtIsNotNull() {
			addCriterion("STARTED_AT is not null");
			return (Criteria) this;
		}

		public Criteria andStartedAtEqualTo(Date value) {
			addCriterion("STARTED_AT =", value, "startedAt");
			return (Criteria) this;
		}

		public Criteria andStartedAtNotEqualTo(Date value) {
			addCriterion("STARTED_AT <>", value, "startedAt");
			return (Criteria) this;
		}

		public Criteria andStartedAtGreaterThan(Date value) {
			addCriterion("STARTED_AT >", value, "startedAt");
			return (Criteria) this;
		}

		public Criteria andStartedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("STARTED_AT >=", value, "startedAt");
			return (Criteria) this;
		}

		public Criteria andStartedAtLessThan(Date value) {
			addCriterion("STARTED_AT <", value, "startedAt");
			return (Criteria) this;
		}

		public Criteria andStartedAtLessThanOrEqualTo(Date value) {
			addCriterion("STARTED_AT <=", value, "startedAt");
			return (Criteria) this;
		}

		public Criteria andStartedAtIn(List<Date> values) {
			addCriterion("STARTED_AT in", values, "startedAt");
			return (Criteria) this;
		}

		public Criteria andStartedAtNotIn(List<Date> values) {
			addCriterion("STARTED_AT not in", values, "startedAt");
			return (Criteria) this;
		}

		public Criteria andStartedAtBetween(Date value1, Date value2) {
			addCriterion("STARTED_AT between", value1, value2, "startedAt");
			return (Criteria) this;
		}

		public Criteria andStartedAtNotBetween(Date value1, Date value2) {
			addCriterion("STARTED_AT not between", value1, value2, "startedAt");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("STATUS like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("STATUS not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andProblemIsNull() {
			addCriterion("PROBLEM is null");
			return (Criteria) this;
		}

		public Criteria andProblemIsNotNull() {
			addCriterion("PROBLEM is not null");
			return (Criteria) this;
		}

		public Criteria andProblemEqualTo(String value) {
			addCriterion("PROBLEM =", value, "problem");
			return (Criteria) this;
		}

		public Criteria andProblemNotEqualTo(String value) {
			addCriterion("PROBLEM <>", value, "problem");
			return (Criteria) this;
		}

		public Criteria andProblemGreaterThan(String value) {
			addCriterion("PROBLEM >", value, "problem");
			return (Criteria) this;
		}

		public Criteria andProblemGreaterThanOrEqualTo(String value) {
			addCriterion("PROBLEM >=", value, "problem");
			return (Criteria) this;
		}

		public Criteria andProblemLessThan(String value) {
			addCriterion("PROBLEM <", value, "problem");
			return (Criteria) this;
		}

		public Criteria andProblemLessThanOrEqualTo(String value) {
			addCriterion("PROBLEM <=", value, "problem");
			return (Criteria) this;
		}

		public Criteria andProblemLike(String value) {
			addCriterion("PROBLEM like", value, "problem");
			return (Criteria) this;
		}

		public Criteria andProblemNotLike(String value) {
			addCriterion("PROBLEM not like", value, "problem");
			return (Criteria) this;
		}

		public Criteria andProblemIn(List<String> values) {
			addCriterion("PROBLEM in", values, "problem");
			return (Criteria) this;
		}

		public Criteria andProblemNotIn(List<String> values) {
			addCriterion("PROBLEM not in", values, "problem");
			return (Criteria) this;
		}

		public Criteria andProblemBetween(String value1, String value2) {
			addCriterion("PROBLEM between", value1, value2, "problem");
			return (Criteria) this;
		}

		public Criteria andProblemNotBetween(String value1, String value2) {
			addCriterion("PROBLEM not between", value1, value2, "problem");
			return (Criteria) this;
		}

		public Criteria andCtIsNull() {
			addCriterion("CT is null");
			return (Criteria) this;
		}

		public Criteria andCtIsNotNull() {
			addCriterion("CT is not null");
			return (Criteria) this;
		}

		public Criteria andCtEqualTo(Integer value) {
			addCriterion("CT =", value, "ct");
			return (Criteria) this;
		}

		public Criteria andCtNotEqualTo(Integer value) {
			addCriterion("CT <>", value, "ct");
			return (Criteria) this;
		}

		public Criteria andCtGreaterThan(Integer value) {
			addCriterion("CT >", value, "ct");
			return (Criteria) this;
		}

		public Criteria andCtGreaterThanOrEqualTo(Integer value) {
			addCriterion("CT >=", value, "ct");
			return (Criteria) this;
		}

		public Criteria andCtLessThan(Integer value) {
			addCriterion("CT <", value, "ct");
			return (Criteria) this;
		}

		public Criteria andCtLessThanOrEqualTo(Integer value) {
			addCriterion("CT <=", value, "ct");
			return (Criteria) this;
		}

		public Criteria andCtIn(List<Integer> values) {
			addCriterion("CT in", values, "ct");
			return (Criteria) this;
		}

		public Criteria andCtNotIn(List<Integer> values) {
			addCriterion("CT not in", values, "ct");
			return (Criteria) this;
		}

		public Criteria andCtBetween(Integer value1, Integer value2) {
			addCriterion("CT between", value1, value2, "ct");
			return (Criteria) this;
		}

		public Criteria andCtNotBetween(Integer value1, Integer value2) {
			addCriterion("CT not between", value1, value2, "ct");
			return (Criteria) this;
		}

		public Criteria andElapsedSecIsNull() {
			addCriterion("ELAPSED_SEC is null");
			return (Criteria) this;
		}

		public Criteria andElapsedSecIsNotNull() {
			addCriterion("ELAPSED_SEC is not null");
			return (Criteria) this;
		}

		public Criteria andElapsedSecEqualTo(Double value) {
			addCriterion("ELAPSED_SEC =", value, "elapsedSec");
			return (Criteria) this;
		}

		public Criteria andElapsedSecNotEqualTo(Double value) {
			addCriterion("ELAPSED_SEC <>", value, "elapsedSec");
			return (Criteria) this;
		}

		public Criteria andElapsedSecGreaterThan(Double value) {
			addCriterion("ELAPSED_SEC >", value, "elapsedSec");
			return (Criteria) this;
		}

		public Criteria andElapsedSecGreaterThanOrEqualTo(Double value) {
			addCriterion("ELAPSED_SEC >=", value, "elapsedSec");
			return (Criteria) this;
		}

		public Criteria andElapsedSecLessThan(Double value) {
			addCriterion("ELAPSED_SEC <", value, "elapsedSec");
			return (Criteria) this;
		}

		public Criteria andElapsedSecLessThanOrEqualTo(Double value) {
			addCriterion("ELAPSED_SEC <=", value, "elapsedSec");
			return (Criteria) this;
		}

		public Criteria andElapsedSecIn(List<Double> values) {
			addCriterion("ELAPSED_SEC in", values, "elapsedSec");
			return (Criteria) this;
		}

		public Criteria andElapsedSecNotIn(List<Double> values) {
			addCriterion("ELAPSED_SEC not in", values, "elapsedSec");
			return (Criteria) this;
		}

		public Criteria andElapsedSecBetween(Double value1, Double value2) {
			addCriterion("ELAPSED_SEC between", value1, value2, "elapsedSec");
			return (Criteria) this;
		}

		public Criteria andElapsedSecNotBetween(Double value1, Double value2) {
			addCriterion("ELAPSED_SEC not between", value1, value2,
					"elapsedSec");
			return (Criteria) this;
		}

		public Criteria andSpecifierIsNull() {
			addCriterion("SPECIFIER is null");
			return (Criteria) this;
		}

		public Criteria andSpecifierIsNotNull() {
			addCriterion("SPECIFIER is not null");
			return (Criteria) this;
		}

		public Criteria andSpecifierEqualTo(String value) {
			addCriterion("SPECIFIER =", value, "specifier");
			return (Criteria) this;
		}

		public Criteria andSpecifierNotEqualTo(String value) {
			addCriterion("SPECIFIER <>", value, "specifier");
			return (Criteria) this;
		}

		public Criteria andSpecifierGreaterThan(String value) {
			addCriterion("SPECIFIER >", value, "specifier");
			return (Criteria) this;
		}

		public Criteria andSpecifierGreaterThanOrEqualTo(String value) {
			addCriterion("SPECIFIER >=", value, "specifier");
			return (Criteria) this;
		}

		public Criteria andSpecifierLessThan(String value) {
			addCriterion("SPECIFIER <", value, "specifier");
			return (Criteria) this;
		}

		public Criteria andSpecifierLessThanOrEqualTo(String value) {
			addCriterion("SPECIFIER <=", value, "specifier");
			return (Criteria) this;
		}

		public Criteria andSpecifierLike(String value) {
			addCriterion("SPECIFIER like", value, "specifier");
			return (Criteria) this;
		}

		public Criteria andSpecifierNotLike(String value) {
			addCriterion("SPECIFIER not like", value, "specifier");
			return (Criteria) this;
		}

		public Criteria andSpecifierIn(List<String> values) {
			addCriterion("SPECIFIER in", values, "specifier");
			return (Criteria) this;
		}

		public Criteria andSpecifierNotIn(List<String> values) {
			addCriterion("SPECIFIER not in", values, "specifier");
			return (Criteria) this;
		}

		public Criteria andSpecifierBetween(String value1, String value2) {
			addCriterion("SPECIFIER between", value1, value2, "specifier");
			return (Criteria) this;
		}

		public Criteria andSpecifierNotBetween(String value1, String value2) {
			addCriterion("SPECIFIER not between", value1, value2, "specifier");
			return (Criteria) this;
		}

		public Criteria andFetcherIsNull() {
			addCriterion("FETCHER is null");
			return (Criteria) this;
		}

		public Criteria andFetcherIsNotNull() {
			addCriterion("FETCHER is not null");
			return (Criteria) this;
		}

		public Criteria andFetcherEqualTo(String value) {
			addCriterion("FETCHER =", value, "fetcher");
			return (Criteria) this;
		}

		public Criteria andFetcherNotEqualTo(String value) {
			addCriterion("FETCHER <>", value, "fetcher");
			return (Criteria) this;
		}

		public Criteria andFetcherGreaterThan(String value) {
			addCriterion("FETCHER >", value, "fetcher");
			return (Criteria) this;
		}

		public Criteria andFetcherGreaterThanOrEqualTo(String value) {
			addCriterion("FETCHER >=", value, "fetcher");
			return (Criteria) this;
		}

		public Criteria andFetcherLessThan(String value) {
			addCriterion("FETCHER <", value, "fetcher");
			return (Criteria) this;
		}

		public Criteria andFetcherLessThanOrEqualTo(String value) {
			addCriterion("FETCHER <=", value, "fetcher");
			return (Criteria) this;
		}

		public Criteria andFetcherLike(String value) {
			addCriterion("FETCHER like", value, "fetcher");
			return (Criteria) this;
		}

		public Criteria andFetcherNotLike(String value) {
			addCriterion("FETCHER not like", value, "fetcher");
			return (Criteria) this;
		}

		public Criteria andFetcherIn(List<String> values) {
			addCriterion("FETCHER in", values, "fetcher");
			return (Criteria) this;
		}

		public Criteria andFetcherNotIn(List<String> values) {
			addCriterion("FETCHER not in", values, "fetcher");
			return (Criteria) this;
		}

		public Criteria andFetcherBetween(String value1, String value2) {
			addCriterion("FETCHER between", value1, value2, "fetcher");
			return (Criteria) this;
		}

		public Criteria andFetcherNotBetween(String value1, String value2) {
			addCriterion("FETCHER not between", value1, value2, "fetcher");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table GW_DATA_PORTAL.FETCH_LOG
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table GW_DATA_PORTAL.FETCH_LOG
     *
     * @mbggenerated do_not_delete_during_merge Fri Mar 30 16:06:26 CDT 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}