package gov.usgs.ngwmn.dm.dao;

import java.util.Date;

public class FetchLog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.FETCH_LOG.FETCHLOG_ID
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	private Integer fetchlogId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.FETCH_LOG.AGENCY_CD
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	private String agencyCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.FETCH_LOG.SITE_NO
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	private String siteNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.FETCH_LOG.DATA_SOURCE
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	private String source;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.FETCH_LOG.STARTED_AT
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	private Date startedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.FETCH_LOG.STATUS
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.FETCH_LOG.PROBLEM
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	private String problem;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.FETCH_LOG.CT
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	private Long ct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.FETCH_LOG.ELAPSED_SEC
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	private Double elapsedSec;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.FETCH_LOG.SPECIFIER
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	private String specifier;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.FETCH_LOG.FETCHER
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	private String fetcher;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.FETCH_LOG.DATA_STREAM
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	private String dataStream;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.FETCH_LOG.FETCHLOG_ID
	 * @return  the value of GW_DATA_PORTAL.FETCH_LOG.FETCHLOG_ID
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	public Integer getFetchlogId() {
		return fetchlogId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.FETCH_LOG.FETCHLOG_ID
	 * @param fetchlogId  the value for GW_DATA_PORTAL.FETCH_LOG.FETCHLOG_ID
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	public void setFetchlogId(Integer fetchlogId) {
		this.fetchlogId = fetchlogId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.FETCH_LOG.AGENCY_CD
	 * @return  the value of GW_DATA_PORTAL.FETCH_LOG.AGENCY_CD
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	public String getAgencyCd() {
		return agencyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.FETCH_LOG.AGENCY_CD
	 * @param agencyCd  the value for GW_DATA_PORTAL.FETCH_LOG.AGENCY_CD
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	public void setAgencyCd(String agencyCd) {
		this.agencyCd = agencyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.FETCH_LOG.SITE_NO
	 * @return  the value of GW_DATA_PORTAL.FETCH_LOG.SITE_NO
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	public String getSiteNo() {
		return siteNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.FETCH_LOG.SITE_NO
	 * @param siteNo  the value for GW_DATA_PORTAL.FETCH_LOG.SITE_NO
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	public void setSiteNo(String siteNo) {
		this.siteNo = siteNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.FETCH_LOG.DATA_SOURCE
	 * @return  the value of GW_DATA_PORTAL.FETCH_LOG.DATA_SOURCE
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	public String getSource() {
		return source;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.FETCH_LOG.DATA_SOURCE
	 * @param source  the value for GW_DATA_PORTAL.FETCH_LOG.DATA_SOURCE
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	public void setSource(String source) {
		this.source = source;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.FETCH_LOG.STARTED_AT
	 * @return  the value of GW_DATA_PORTAL.FETCH_LOG.STARTED_AT
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	public Date getStartedAt() {
		return startedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.FETCH_LOG.STARTED_AT
	 * @param startedAt  the value for GW_DATA_PORTAL.FETCH_LOG.STARTED_AT
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	public void setStartedAt(Date startedAt) {
		this.startedAt = startedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.FETCH_LOG.STATUS
	 * @return  the value of GW_DATA_PORTAL.FETCH_LOG.STATUS
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.FETCH_LOG.STATUS
	 * @param status  the value for GW_DATA_PORTAL.FETCH_LOG.STATUS
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.FETCH_LOG.PROBLEM
	 * @return  the value of GW_DATA_PORTAL.FETCH_LOG.PROBLEM
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	public String getProblem() {
		return problem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.FETCH_LOG.PROBLEM
	 * @param problem  the value for GW_DATA_PORTAL.FETCH_LOG.PROBLEM
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	public void setProblem(String problem) {
		this.problem = problem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.FETCH_LOG.CT
	 * @return  the value of GW_DATA_PORTAL.FETCH_LOG.CT
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	public Long getCt() {
		return ct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.FETCH_LOG.CT
	 * @param ct  the value for GW_DATA_PORTAL.FETCH_LOG.CT
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	public void setCt(Long ct) {
		this.ct = ct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.FETCH_LOG.ELAPSED_SEC
	 * @return  the value of GW_DATA_PORTAL.FETCH_LOG.ELAPSED_SEC
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	public Double getElapsedSec() {
		return elapsedSec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.FETCH_LOG.ELAPSED_SEC
	 * @param elapsedSec  the value for GW_DATA_PORTAL.FETCH_LOG.ELAPSED_SEC
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	public void setElapsedSec(Double elapsedSec) {
		this.elapsedSec = elapsedSec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.FETCH_LOG.SPECIFIER
	 * @return  the value of GW_DATA_PORTAL.FETCH_LOG.SPECIFIER
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	public String getSpecifier() {
		return specifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.FETCH_LOG.SPECIFIER
	 * @param specifier  the value for GW_DATA_PORTAL.FETCH_LOG.SPECIFIER
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	public void setSpecifier(String specifier) {
		this.specifier = specifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.FETCH_LOG.FETCHER
	 * @return  the value of GW_DATA_PORTAL.FETCH_LOG.FETCHER
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	public String getFetcher() {
		return fetcher;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.FETCH_LOG.FETCHER
	 * @param fetcher  the value for GW_DATA_PORTAL.FETCH_LOG.FETCHER
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	public void setFetcher(String fetcher) {
		this.fetcher = fetcher;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.FETCH_LOG.DATA_STREAM
	 * @return  the value of GW_DATA_PORTAL.FETCH_LOG.DATA_STREAM
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	public String getDataStream() {
		return dataStream;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.FETCH_LOG.DATA_STREAM
	 * @param dataStream  the value for GW_DATA_PORTAL.FETCH_LOG.DATA_STREAM
	 * @mbggenerated  Fri May 25 11:07:09 CDT 2012
	 */
	public void setDataStream(String dataStream) {
		this.dataStream = dataStream;
	}
	
	

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("FetchLog [fetchlogId=").append(fetchlogId)
				.append(", startedAt=").append(startedAt)
				.append(", well=").append(getWell())
				.append(", datatype=").append(dataStream)
				.append("]");
		return builder.toString();
	}

	public void setWell(WellRegistryKey key) {
		setAgencyCd(key.getAgencyCd());
		setSiteNo(key.getSiteNo());
	}
	
	public WellRegistryKey getWell() {
		return new WellRegistryKey(getAgencyCd(), getSiteNo());
	}
}