package gov.usgs.ngwmn.dm.dao;

import gov.usgs.ngwmn.dm.dao.FetchLog;
import gov.usgs.ngwmn.dm.dao.FetchLogExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface FetchLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.FETCH_LOG
	 * @mbggenerated  Fri Mar 30 17:04:19 CDT 2012
	 */
	int countByExample(FetchLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.FETCH_LOG
	 * @mbggenerated  Fri Mar 30 17:04:19 CDT 2012
	 */
	int deleteByExample(FetchLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.FETCH_LOG
	 * @mbggenerated  Fri Mar 30 17:04:19 CDT 2012
	 */
	@Delete({ "delete from GW_DATA_PORTAL.FETCH_LOG",
			"where FETCHLOG_ID = #{fetchlogId,jdbcType=NUMBER}" })
	int deleteByPrimaryKey(Integer fetchlogId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.FETCH_LOG
	 * @mbggenerated  Fri Mar 30 17:04:19 CDT 2012
	 */
	@Insert({
			"insert into GW_DATA_PORTAL.FETCH_LOG (FETCHLOG_ID, DATA_SOURCE, ",
			"STARTED_AT, STATUS, ",
			"PROBLEM, CT, ELAPSED_SEC, ",
			"SPECIFIER)",
			"values (#{fetchlogId,jdbcType=NUMBER}, #{source,jdbcType=VARCHAR}, ",
			"#{startedAt,jdbcType=TIMESTAMP}, #{status,jdbcType=CHAR}, ",
			"#{problem,jdbcType=VARCHAR}, #{ct,jdbcType=NUMBER}, #{elapsedSec,jdbcType=FLOAT}, ",
			"#{specifier,jdbcType=VARCHAR})" })
	int insert(FetchLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.FETCH_LOG
	 * @mbggenerated  Fri Mar 30 17:04:19 CDT 2012
	 */
	int insertSelective(FetchLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.FETCH_LOG
	 * @mbggenerated  Fri Mar 30 17:04:19 CDT 2012
	 */
	List<FetchLog> selectByExample(FetchLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.FETCH_LOG
	 * @mbggenerated  Fri Mar 30 17:04:19 CDT 2012
	 */
	@Select({
			"select",
			"FETCHLOG_ID, DATA_SOURCE, STARTED_AT, STATUS, PROBLEM, CT, ELAPSED_SEC, SPECIFIER",
			"from GW_DATA_PORTAL.FETCH_LOG",
			"where FETCHLOG_ID = #{fetchlogId,jdbcType=NUMBER}" })
	@ResultMap("BaseResultMap")
	FetchLog selectByPrimaryKey(Integer fetchlogId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.FETCH_LOG
	 * @mbggenerated  Fri Mar 30 17:04:19 CDT 2012
	 */
	int updateByExampleSelective(@Param("record") FetchLog record,
			@Param("example") FetchLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.FETCH_LOG
	 * @mbggenerated  Fri Mar 30 17:04:19 CDT 2012
	 */
	int updateByExample(@Param("record") FetchLog record,
			@Param("example") FetchLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.FETCH_LOG
	 * @mbggenerated  Fri Mar 30 17:04:19 CDT 2012
	 */
	int updateByPrimaryKeySelective(FetchLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.FETCH_LOG
	 * @mbggenerated  Fri Mar 30 17:04:19 CDT 2012
	 */
	@Update({ "update GW_DATA_PORTAL.FETCH_LOG",
			"set DATA_SOURCE = #{source,jdbcType=VARCHAR},",
			"STARTED_AT = #{startedAt,jdbcType=TIMESTAMP},",
			"STATUS = #{status,jdbcType=CHAR},",
			"PROBLEM = #{problem,jdbcType=VARCHAR},",
			"CT = #{ct,jdbcType=NUMBER},",
			"ELAPSED_SEC = #{elapsedSec,jdbcType=FLOAT},",
			"SPECIFIER = #{specifier,jdbcType=VARCHAR}",
			"where FETCHLOG_ID = #{fetchlogId,jdbcType=NUMBER}" })
	int updateByPrimaryKey(FetchLog record);
}