package gov.usgs.ngwmn.dm.dao;

public class LogDataQuality {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GW_DATA_PORTAL.LOG_DATA_QUALITY.MD5
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    private String md5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GW_DATA_PORTAL.LOG_DATA_QUALITY.DEPTH
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    private Double depth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GW_DATA_PORTAL.LOG_DATA_QUALITY.LATITUDE
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GW_DATA_PORTAL.LOG_DATA_QUALITY.LONGITUDE
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GW_DATA_PORTAL.LOG_DATA_QUALITY.LITHOLOGYCOUNT
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    private Integer lithologycount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GW_DATA_PORTAL.LOG_DATA_QUALITY.CONSTRUCTIONCOUNT
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    private Integer constructioncount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GW_DATA_PORTAL.LOG_DATA_QUALITY.MD5
     *
     * @return the value of GW_DATA_PORTAL.LOG_DATA_QUALITY.MD5
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GW_DATA_PORTAL.LOG_DATA_QUALITY.MD5
     *
     * @param md5 the value for GW_DATA_PORTAL.LOG_DATA_QUALITY.MD5
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    public void setMd5(String md5) {
        this.md5 = md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GW_DATA_PORTAL.LOG_DATA_QUALITY.DEPTH
     *
     * @return the value of GW_DATA_PORTAL.LOG_DATA_QUALITY.DEPTH
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    public Double getDepth() {
        return depth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GW_DATA_PORTAL.LOG_DATA_QUALITY.DEPTH
     *
     * @param depth the value for GW_DATA_PORTAL.LOG_DATA_QUALITY.DEPTH
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    public void setDepth(Double depth) {
        this.depth = depth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GW_DATA_PORTAL.LOG_DATA_QUALITY.LATITUDE
     *
     * @return the value of GW_DATA_PORTAL.LOG_DATA_QUALITY.LATITUDE
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GW_DATA_PORTAL.LOG_DATA_QUALITY.LATITUDE
     *
     * @param latitude the value for GW_DATA_PORTAL.LOG_DATA_QUALITY.LATITUDE
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GW_DATA_PORTAL.LOG_DATA_QUALITY.LONGITUDE
     *
     * @return the value of GW_DATA_PORTAL.LOG_DATA_QUALITY.LONGITUDE
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GW_DATA_PORTAL.LOG_DATA_QUALITY.LONGITUDE
     *
     * @param longitude the value for GW_DATA_PORTAL.LOG_DATA_QUALITY.LONGITUDE
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GW_DATA_PORTAL.LOG_DATA_QUALITY.LITHOLOGYCOUNT
     *
     * @return the value of GW_DATA_PORTAL.LOG_DATA_QUALITY.LITHOLOGYCOUNT
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    public Integer getLithologycount() {
        return lithologycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GW_DATA_PORTAL.LOG_DATA_QUALITY.LITHOLOGYCOUNT
     *
     * @param lithologycount the value for GW_DATA_PORTAL.LOG_DATA_QUALITY.LITHOLOGYCOUNT
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    public void setLithologycount(Integer lithologycount) {
        this.lithologycount = lithologycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GW_DATA_PORTAL.LOG_DATA_QUALITY.CONSTRUCTIONCOUNT
     *
     * @return the value of GW_DATA_PORTAL.LOG_DATA_QUALITY.CONSTRUCTIONCOUNT
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    public Integer getConstructioncount() {
        return constructioncount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GW_DATA_PORTAL.LOG_DATA_QUALITY.CONSTRUCTIONCOUNT
     *
     * @param constructioncount the value for GW_DATA_PORTAL.LOG_DATA_QUALITY.CONSTRUCTIONCOUNT
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    public void setConstructioncount(Integer constructioncount) {
        this.constructioncount = constructioncount;
    }
}