package gov.usgs.ngwmn.dm.dao;

public class QualityDataQualityKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GW_DATA_PORTAL.QUALITY_DATA_QUALITY.CONSITUENT
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    private String consituent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GW_DATA_PORTAL.QUALITY_DATA_QUALITY.MD5
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    private String md5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GW_DATA_PORTAL.QUALITY_DATA_QUALITY.CONSITUENT
     *
     * @return the value of GW_DATA_PORTAL.QUALITY_DATA_QUALITY.CONSITUENT
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    public String getConsituent() {
        return consituent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GW_DATA_PORTAL.QUALITY_DATA_QUALITY.CONSITUENT
     *
     * @param consituent the value for GW_DATA_PORTAL.QUALITY_DATA_QUALITY.CONSITUENT
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    public void setConsituent(String consituent) {
        this.consituent = consituent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GW_DATA_PORTAL.QUALITY_DATA_QUALITY.MD5
     *
     * @return the value of GW_DATA_PORTAL.QUALITY_DATA_QUALITY.MD5
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GW_DATA_PORTAL.QUALITY_DATA_QUALITY.MD5
     *
     * @param md5 the value for GW_DATA_PORTAL.QUALITY_DATA_QUALITY.MD5
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    public void setMd5(String md5) {
        this.md5 = md5;
    }
}