package gov.usgs.ngwmn.dm.dao;

import gov.usgs.ngwmn.dm.dao.QualityDataQuality;
import gov.usgs.ngwmn.dm.dao.QualityDataQualityExample;
import gov.usgs.ngwmn.dm.dao.QualityDataQualityKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface QualityDataQualityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GW_DATA_PORTAL.QUALITY_DATA_QUALITY
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    int countByExample(QualityDataQualityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GW_DATA_PORTAL.QUALITY_DATA_QUALITY
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    int deleteByExample(QualityDataQualityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GW_DATA_PORTAL.QUALITY_DATA_QUALITY
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    @Delete({
        "delete from GW_DATA_PORTAL.QUALITY_DATA_QUALITY",
        "where CONSITUENT = #{consituent,jdbcType=VARCHAR}",
          "and MD5 = #{md5,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(QualityDataQualityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GW_DATA_PORTAL.QUALITY_DATA_QUALITY
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    @Insert({
        "insert into GW_DATA_PORTAL.QUALITY_DATA_QUALITY (CONSITUENT, MD5, ",
        "FIRSTDATE, LASTDATE, ",
        "CT)",
        "values (#{consituent,jdbcType=VARCHAR}, #{md5,jdbcType=CHAR}, ",
        "#{firstdate,jdbcType=TIMESTAMP}, #{lastdate,jdbcType=TIMESTAMP}, ",
        "#{ct,jdbcType=DECIMAL})"
    })
    int insert(QualityDataQuality record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GW_DATA_PORTAL.QUALITY_DATA_QUALITY
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    int insertSelective(QualityDataQuality record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GW_DATA_PORTAL.QUALITY_DATA_QUALITY
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    List<QualityDataQuality> selectByExample(QualityDataQualityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GW_DATA_PORTAL.QUALITY_DATA_QUALITY
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    @Select({
        "select",
        "CONSITUENT, MD5, FIRSTDATE, LASTDATE, CT",
        "from GW_DATA_PORTAL.QUALITY_DATA_QUALITY",
        "where CONSITUENT = #{consituent,jdbcType=VARCHAR}",
          "and MD5 = #{md5,jdbcType=CHAR}"
    })
    @ResultMap("BaseResultMap")
    QualityDataQuality selectByPrimaryKey(QualityDataQualityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GW_DATA_PORTAL.QUALITY_DATA_QUALITY
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    int updateByExampleSelective(@Param("record") QualityDataQuality record, @Param("example") QualityDataQualityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GW_DATA_PORTAL.QUALITY_DATA_QUALITY
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    int updateByExample(@Param("record") QualityDataQuality record, @Param("example") QualityDataQualityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GW_DATA_PORTAL.QUALITY_DATA_QUALITY
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    int updateByPrimaryKeySelective(QualityDataQuality record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GW_DATA_PORTAL.QUALITY_DATA_QUALITY
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    @Update({
        "update GW_DATA_PORTAL.QUALITY_DATA_QUALITY",
        "set FIRSTDATE = #{firstdate,jdbcType=TIMESTAMP},",
          "LASTDATE = #{lastdate,jdbcType=TIMESTAMP},",
          "CT = #{ct,jdbcType=DECIMAL}",
        "where CONSITUENT = #{consituent,jdbcType=VARCHAR}",
          "and MD5 = #{md5,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(QualityDataQuality record);
}