package gov.usgs.ngwmn.dm.dao;

import gov.usgs.ngwmn.dm.dao.WaterlevelDataQuality;
import gov.usgs.ngwmn.dm.dao.WaterlevelDataQualityExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface WaterlevelDataQualityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    int countByExample(WaterlevelDataQualityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    int deleteByExample(WaterlevelDataQualityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    @Delete({
        "delete from GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY",
        "where MD5 = #{md5,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String md5);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    @Insert({
        "insert into GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY (MD5, FIRSTDATE, ",
        "LASTDATE, CT)",
        "values (#{md5,jdbcType=CHAR}, #{firstdate,jdbcType=TIMESTAMP}, ",
        "#{lastdate,jdbcType=TIMESTAMP}, #{ct,jdbcType=DECIMAL})"
    })
    int insert(WaterlevelDataQuality record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    int insertSelective(WaterlevelDataQuality record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    List<WaterlevelDataQuality> selectByExample(WaterlevelDataQualityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    @Select({
        "select",
        "MD5, FIRSTDATE, LASTDATE, CT",
        "from GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY",
        "where MD5 = #{md5,jdbcType=CHAR}"
    })
    @ResultMap("BaseResultMap")
    WaterlevelDataQuality selectByPrimaryKey(String md5);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    int updateByExampleSelective(@Param("record") WaterlevelDataQuality record, @Param("example") WaterlevelDataQualityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    int updateByExample(@Param("record") WaterlevelDataQuality record, @Param("example") WaterlevelDataQualityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    int updateByPrimaryKeySelective(WaterlevelDataQuality record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    @Update({
        "update GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY",
        "set FIRSTDATE = #{firstdate,jdbcType=TIMESTAMP},",
          "LASTDATE = #{lastdate,jdbcType=TIMESTAMP},",
          "CT = #{ct,jdbcType=DECIMAL}",
        "where MD5 = #{md5,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(WaterlevelDataQuality record);
}