package gov.usgs.ngwmn.dm.dao;

import java.util.Date;

public class WaterlevelDataQuality {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY.MD5
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    private String md5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY.FIRSTDATE
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    private Date firstdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY.LASTDATE
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    private Date lastdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY.CT
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    private Integer ct;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY.MD5
     *
     * @return the value of GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY.MD5
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY.MD5
     *
     * @param md5 the value for GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY.MD5
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    public void setMd5(String md5) {
        this.md5 = md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY.FIRSTDATE
     *
     * @return the value of GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY.FIRSTDATE
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    public Date getFirstdate() {
        return firstdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY.FIRSTDATE
     *
     * @param firstdate the value for GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY.FIRSTDATE
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    public void setFirstdate(Date firstdate) {
        this.firstdate = firstdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY.LASTDATE
     *
     * @return the value of GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY.LASTDATE
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    public Date getLastdate() {
        return lastdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY.LASTDATE
     *
     * @param lastdate the value for GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY.LASTDATE
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    public void setLastdate(Date lastdate) {
        this.lastdate = lastdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY.CT
     *
     * @return the value of GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY.CT
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    public Integer getCt() {
        return ct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY.CT
     *
     * @param ct the value for GW_DATA_PORTAL.WATERLEVEL_DATA_QUALITY.CT
     *
     * @mbggenerated Fri May 25 11:07:09 CDT 2012
     */
    public void setCt(Integer ct) {
        this.ct = ct;
    }
}