package gov.usgs.ngwmn.dm.dao;

public class WellRegistryKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.AGENCY_CD
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String agencyCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.SITE_NO
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String siteNo;

	public WellRegistryKey(String agencyCd, String siteNo) {
		this.agencyCd = agencyCd;
		this.siteNo = siteNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.AGENCY_CD
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.AGENCY_CD
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getAgencyCd() {
		return agencyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.SITE_NO
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.SITE_NO
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getSiteNo() {
		return siteNo;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((agencyCd == null) ? 0 : agencyCd.hashCode());
		result = prime * result + ((siteNo == null) ? 0 : siteNo.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		WellRegistryKey other = (WellRegistryKey) obj;
		if (agencyCd == null) {
			if (other.agencyCd != null)
				return false;
		} else if (!agencyCd.equals(other.agencyCd))
			return false;
		if (siteNo == null) {
			if (other.siteNo != null)
				return false;
		} else if (!siteNo.equals(other.siteNo))
			return false;
		return true;
	}

	
	
}
