package gov.usgs.ngwmn.dm.dao;

public class WellRegistryKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.AGENCY_CD
	 * @mbggenerated  Fri Mar 30 17:59:43 CDT 2012
	 */
	private String agencyCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.SITE_NO
	 * @mbggenerated  Fri Mar 30 17:59:43 CDT 2012
	 */
	private String siteNo;

	public WellRegistryKey(String agencyCd, String siteNo) {
		this.agencyCd = agencyCd;
		this.siteNo = siteNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.AGENCY_CD
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.AGENCY_CD
	 * @mbggenerated  Fri Mar 30 17:59:43 CDT 2012
	 */
	public String getAgencyCd() {
		return agencyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.SITE_NO
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.SITE_NO
	 * @mbggenerated  Fri Mar 30 17:59:43 CDT 2012
	 */
	public String getSiteNo() {
		return siteNo;
	}

	
}
