package gov.usgs.ngwmn.dm.dao;

import java.util.Date;

public class WellRegistry extends WellRegistryKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.AGENCY_NM
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String agencyNm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.AGENCY_MED
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String agencyMed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.SITE_NAME
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String siteName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.DEC_LAT_VA
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private Double decLatVa;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.DEC_LONG_VA
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private Double decLongVa;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.HORZ_DATUM
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String horzDatum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.ALT_VA
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private Double altVa;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.ALT_DATUM_CD
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String altDatumCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.NAT_AQUIFER_CD
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String natAquiferCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.NAT_AQFR_DESC
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String natAqfrDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.LOCAL_AQUIFER_NAME
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String localAquiferName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_SN_FLAG
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String qwSnFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_BASELINE_FLAG
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String qwBaselineFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_CHARS
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String qwWellChars;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_TYPE
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String qwWellType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_SN_FLAG
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String wlSnFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_BASELINE_FLAG
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String wlBaselineFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_CHARS
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String wlWellChars;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_TYPE
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String wlWellType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.DATA_PROVIDER
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String dataProvider;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_SYS_NAME
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String qwSysName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_SYS_NAME
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String wlSysName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.INSERT_DATE
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private Date insertDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.MY_SITEID
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String mySiteid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.DISPLAY_FLAG
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String displayFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_DATA_PROVIDER
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String wlDataProvider;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_DATA_PROVIDER
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String qwDataProvider;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.LITH_DATA_PROVIDER
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String lithDataProvider;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.CONST_DATA_PROVIDER
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String constDataProvider;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.WELL_DEPTH
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private Double wellDepth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.WELL_DEPTH_UNITS
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String wellDepthUnits;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.LINK
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String link;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_PURPOSE
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String wlWellPurpose;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_PURPOSE
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String qwWellPurpose;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_PURPOSE_NOTES
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String wlWellPurposeNotes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_PURPOSE_NOTES
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String qwWellPurposeNotes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.STATE_CD
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private Integer stateCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.COUNTY_CD
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private Integer countyCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.UPDATE_DATE
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.ALT_UNITS
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private Integer altUnits;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.LOCAL_AQUIFER_CD
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	private String localAquiferCd;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.AGENCY_NM
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.AGENCY_NM
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getAgencyNm() {
		return agencyNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.AGENCY_MED
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.AGENCY_MED
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getAgencyMed() {
		return agencyMed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.SITE_NAME
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.SITE_NAME
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getSiteName() {
		return siteName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.DEC_LAT_VA
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.DEC_LAT_VA
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public Double getDecLatVa() {
		return decLatVa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.DEC_LONG_VA
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.DEC_LONG_VA
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public Double getDecLongVa() {
		return decLongVa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.HORZ_DATUM
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.HORZ_DATUM
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getHorzDatum() {
		return horzDatum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.ALT_VA
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.ALT_VA
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public Double getAltVa() {
		return altVa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.ALT_DATUM_CD
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.ALT_DATUM_CD
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getAltDatumCd() {
		return altDatumCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.NAT_AQUIFER_CD
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.NAT_AQUIFER_CD
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getNatAquiferCd() {
		return natAquiferCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.NAT_AQFR_DESC
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.NAT_AQFR_DESC
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getNatAqfrDesc() {
		return natAqfrDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.LOCAL_AQUIFER_NAME
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.LOCAL_AQUIFER_NAME
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getLocalAquiferName() {
		return localAquiferName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_SN_FLAG
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.QW_SN_FLAG
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getQwSnFlag() {
		return qwSnFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_BASELINE_FLAG
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.QW_BASELINE_FLAG
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getQwBaselineFlag() {
		return qwBaselineFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_CHARS
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_CHARS
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getQwWellChars() {
		return qwWellChars;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_TYPE
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_TYPE
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getQwWellType() {
		return qwWellType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_SN_FLAG
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.WL_SN_FLAG
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getWlSnFlag() {
		return wlSnFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_BASELINE_FLAG
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.WL_BASELINE_FLAG
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getWlBaselineFlag() {
		return wlBaselineFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_CHARS
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_CHARS
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getWlWellChars() {
		return wlWellChars;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_TYPE
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_TYPE
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getWlWellType() {
		return wlWellType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.DATA_PROVIDER
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.DATA_PROVIDER
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getDataProvider() {
		return dataProvider;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_SYS_NAME
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.QW_SYS_NAME
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getQwSysName() {
		return qwSysName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_SYS_NAME
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.WL_SYS_NAME
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getWlSysName() {
		return wlSysName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.INSERT_DATE
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.INSERT_DATE
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public Date getInsertDate() {
		return insertDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.MY_SITEID
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.MY_SITEID
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getMySiteid() {
		return mySiteid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.DISPLAY_FLAG
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.DISPLAY_FLAG
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getDisplayFlag() {
		return displayFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_DATA_PROVIDER
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.WL_DATA_PROVIDER
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getWlDataProvider() {
		return wlDataProvider;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_DATA_PROVIDER
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.QW_DATA_PROVIDER
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getQwDataProvider() {
		return qwDataProvider;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.LITH_DATA_PROVIDER
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.LITH_DATA_PROVIDER
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getLithDataProvider() {
		return lithDataProvider;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.CONST_DATA_PROVIDER
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.CONST_DATA_PROVIDER
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getConstDataProvider() {
		return constDataProvider;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.WELL_DEPTH
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.WELL_DEPTH
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public Double getWellDepth() {
		return wellDepth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.WELL_DEPTH_UNITS
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.WELL_DEPTH_UNITS
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getWellDepthUnits() {
		return wellDepthUnits;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.LINK
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.LINK
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getLink() {
		return link;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_PURPOSE
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_PURPOSE
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getWlWellPurpose() {
		return wlWellPurpose;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_PURPOSE
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_PURPOSE
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getQwWellPurpose() {
		return qwWellPurpose;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_PURPOSE_NOTES
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_PURPOSE_NOTES
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getWlWellPurposeNotes() {
		return wlWellPurposeNotes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_PURPOSE_NOTES
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_PURPOSE_NOTES
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getQwWellPurposeNotes() {
		return qwWellPurposeNotes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.STATE_CD
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.STATE_CD
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public Integer getStateCd() {
		return stateCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.COUNTY_CD
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.COUNTY_CD
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public Integer getCountyCd() {
		return countyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.UPDATE_DATE
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.UPDATE_DATE
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.ALT_UNITS
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.ALT_UNITS
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public Integer getAltUnits() {
		return altUnits;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.LOCAL_AQUIFER_CD
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.LOCAL_AQUIFER_CD
	 * @mbggenerated  Thu Apr 05 11:33:44 CDT 2012
	 */
	public String getLocalAquiferCd() {
		return localAquiferCd;
	}

	public WellRegistry(String agencyCd, String siteNo, String agencyNm,
			String agencyMed, String siteName, Double decLatVa,
			Double decLongVa, String horzDatum, Double altVa,
			String altDatumCd, String natAquiferCd, String natAqfrDesc,
			String localAquiferName, String qwSnFlag, String qwBaselineFlag,
			String qwWellChars, String qwWellType, String wlSnFlag,
			String wlBaselineFlag, String wlWellChars, String wlWellType,
			String dataProvider, String qwSysName, String wlSysName,
			Date insertDate, String mySiteid, String displayFlag,
			String wlDataProvider, String qwDataProvider,
			String lithDataProvider, String constDataProvider,
			Double wellDepth, String wellDepthUnits, String link,
			String wlWellPurpose, String qwWellPurpose,
			String wlWellPurposeNotes, String qwWellPurposeNotes,
			Integer stateCd, Integer countyCd, Date updateDate,
			Integer altUnits, String localAquiferCd) {
		super(agencyCd, siteNo);
		this.agencyNm = agencyNm;
		this.agencyMed = agencyMed;
		this.siteName = siteName;
		this.decLatVa = decLatVa;
		this.decLongVa = decLongVa;
		this.horzDatum = horzDatum;
		this.altVa = altVa;
		this.altDatumCd = altDatumCd;
		this.natAquiferCd = natAquiferCd;
		this.natAqfrDesc = natAqfrDesc;
		this.localAquiferName = localAquiferName;
		this.qwSnFlag = qwSnFlag;
		this.qwBaselineFlag = qwBaselineFlag;
		this.qwWellChars = qwWellChars;
		this.qwWellType = qwWellType;
		this.wlSnFlag = wlSnFlag;
		this.wlBaselineFlag = wlBaselineFlag;
		this.wlWellChars = wlWellChars;
		this.wlWellType = wlWellType;
		this.dataProvider = dataProvider;
		this.qwSysName = qwSysName;
		this.wlSysName = wlSysName;
		this.insertDate = insertDate;
		this.mySiteid = mySiteid;
		this.displayFlag = displayFlag;
		this.wlDataProvider = wlDataProvider;
		this.qwDataProvider = qwDataProvider;
		this.lithDataProvider = lithDataProvider;
		this.constDataProvider = constDataProvider;
		this.wellDepth = wellDepth;
		this.wellDepthUnits = wellDepthUnits;
		this.link = link;
		this.wlWellPurpose = wlWellPurpose;
		this.qwWellPurpose = qwWellPurpose;
		this.wlWellPurposeNotes = wlWellPurposeNotes;
		this.qwWellPurposeNotes = qwWellPurposeNotes;
		this.stateCd = stateCd;
		this.countyCd = countyCd;
		this.updateDate = updateDate;
		this.altUnits = altUnits;
		this.localAquiferCd = localAquiferCd;
	}

	public WellRegistry() {
		super(null,null);
	}
}