package gov.usgs.ngwmn.dm.dao;

import gov.usgs.ngwmn.dm.dao.WellRegistry;
import gov.usgs.ngwmn.dm.dao.WellRegistryExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class WellRegistryDAOImpl extends SqlMapClientDaoSupport implements WellRegistryDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.WELL_REGISTRY
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public WellRegistryDAOImpl() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.WELL_REGISTRY
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public int countByExample(WellRegistryExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"GW_DATA_PORTAL_WELL_REGISTRY.countByExample", example);
		return count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.WELL_REGISTRY
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	@SuppressWarnings("unchecked")
	public List<WellRegistry> selectByExample(WellRegistryExample example) {
		List<WellRegistry> list = getSqlMapClientTemplate().queryForList(
				"GW_DATA_PORTAL_WELL_REGISTRY.selectByExample", example);
		return list;
	}

	@Override
	public WellRegistry findByKey(String agencyID, String wellID) {
		WellRegistryKey k = new WellRegistryKey(agencyID, wellID);
		return (WellRegistry) getSqlMapClientTemplate().queryForObject("selectByKey", k);
	}
	
	@Override
	public List<WellRegistry> selectAll() {
		WellRegistryExample filter = new WellRegistryExample();
		return selectByExample(filter);
	}

}