package gov.usgs.ngwmn.dm.dao;

import java.math.BigDecimal;
import java.util.Date;

public class WellRegistry {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.AGENCY_CD
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String agencyCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.AGENCY_NM
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String agencyNm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.AGENCY_MED
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String agencyMed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.SITE_NO
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String siteNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.SITE_NAME
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String siteName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.DEC_LAT_VA
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private Double decLatVa;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.DEC_LONG_VA
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private Double decLongVa;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.HORZ_DATUM
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String horzDatum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.ALT_VA
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private Double altVa;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.ALT_DATUM_CD
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String altDatumCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.NAT_AQUIFER_CD
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String natAquiferCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.NAT_AQFR_DESC
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String natAqfrDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.LOCAL_AQUIFER_NAME
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String localAquiferName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_SN_FLAG
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String qwSnFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_BASELINE_FLAG
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String qwBaselineFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_CHARS
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String qwWellChars;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_TYPE
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String qwWellType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_SN_FLAG
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String wlSnFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_BASELINE_FLAG
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String wlBaselineFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_CHARS
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String wlWellChars;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_TYPE
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String wlWellType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.DATA_PROVIDER
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String dataProvider;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_SYS_NAME
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String qwSysName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_SYS_NAME
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String wlSysName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.INSERT_DATE
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private Date insertDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.MY_SITEID
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String mySiteid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.DISPLAY_FLAG
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String displayFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_DATA_PROVIDER
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String wlDataProvider;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_DATA_PROVIDER
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String qwDataProvider;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.LITH_DATA_PROVIDER
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String lithDataProvider;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.CONST_DATA_PROVIDER
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String constDataProvider;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.WELL_DEPTH
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private Float wellDepth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.WELL_DEPTH_UNITS
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String wellDepthUnits;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.LINK
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String link;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_PURPOSE
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String wlWellPurpose;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_PURPOSE
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String qwWellPurpose;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_PURPOSE_NOTES
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String wlWellPurposeNotes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_PURPOSE_NOTES
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String qwWellPurposeNotes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.STATE_CD
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private Integer stateCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.COUNTY_CD
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private Integer countyCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.UPDATE_DATE
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.ALT_UNITS
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private Integer altUnits;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GW_DATA_PORTAL.WELL_REGISTRY.LOCAL_AQUIFER_CD
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	private String localAquiferCd;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.AGENCY_CD
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.AGENCY_CD
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getAgencyCd() {
		return agencyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.AGENCY_CD
	 * @param agencyCd  the value for GW_DATA_PORTAL.WELL_REGISTRY.AGENCY_CD
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setAgencyCd(String agencyCd) {
		this.agencyCd = agencyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.AGENCY_NM
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.AGENCY_NM
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getAgencyNm() {
		return agencyNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.AGENCY_NM
	 * @param agencyNm  the value for GW_DATA_PORTAL.WELL_REGISTRY.AGENCY_NM
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setAgencyNm(String agencyNm) {
		this.agencyNm = agencyNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.AGENCY_MED
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.AGENCY_MED
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getAgencyMed() {
		return agencyMed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.AGENCY_MED
	 * @param agencyMed  the value for GW_DATA_PORTAL.WELL_REGISTRY.AGENCY_MED
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setAgencyMed(String agencyMed) {
		this.agencyMed = agencyMed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.SITE_NO
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.SITE_NO
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getSiteNo() {
		return siteNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.SITE_NO
	 * @param siteNo  the value for GW_DATA_PORTAL.WELL_REGISTRY.SITE_NO
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setSiteNo(String siteNo) {
		this.siteNo = siteNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.SITE_NAME
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.SITE_NAME
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getSiteName() {
		return siteName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.SITE_NAME
	 * @param siteName  the value for GW_DATA_PORTAL.WELL_REGISTRY.SITE_NAME
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setSiteName(String siteName) {
		this.siteName = siteName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.DEC_LAT_VA
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.DEC_LAT_VA
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public Double getDecLatVa() {
		return decLatVa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.DEC_LAT_VA
	 * @param decLatVa  the value for GW_DATA_PORTAL.WELL_REGISTRY.DEC_LAT_VA
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setDecLatVa(Double decLatVa) {
		this.decLatVa = decLatVa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.DEC_LONG_VA
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.DEC_LONG_VA
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public Double getDecLongVa() {
		return decLongVa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.DEC_LONG_VA
	 * @param decLongVa  the value for GW_DATA_PORTAL.WELL_REGISTRY.DEC_LONG_VA
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setDecLongVa(Double decLongVa) {
		this.decLongVa = decLongVa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.HORZ_DATUM
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.HORZ_DATUM
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getHorzDatum() {
		return horzDatum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.HORZ_DATUM
	 * @param horzDatum  the value for GW_DATA_PORTAL.WELL_REGISTRY.HORZ_DATUM
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setHorzDatum(String horzDatum) {
		this.horzDatum = horzDatum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.ALT_VA
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.ALT_VA
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public Double getAltVa() {
		return altVa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.ALT_VA
	 * @param altVa  the value for GW_DATA_PORTAL.WELL_REGISTRY.ALT_VA
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setAltVa(Double altVa) {
		this.altVa = altVa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.ALT_DATUM_CD
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.ALT_DATUM_CD
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getAltDatumCd() {
		return altDatumCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.ALT_DATUM_CD
	 * @param altDatumCd  the value for GW_DATA_PORTAL.WELL_REGISTRY.ALT_DATUM_CD
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setAltDatumCd(String altDatumCd) {
		this.altDatumCd = altDatumCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.NAT_AQUIFER_CD
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.NAT_AQUIFER_CD
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getNatAquiferCd() {
		return natAquiferCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.NAT_AQUIFER_CD
	 * @param natAquiferCd  the value for GW_DATA_PORTAL.WELL_REGISTRY.NAT_AQUIFER_CD
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setNatAquiferCd(String natAquiferCd) {
		this.natAquiferCd = natAquiferCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.NAT_AQFR_DESC
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.NAT_AQFR_DESC
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getNatAqfrDesc() {
		return natAqfrDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.NAT_AQFR_DESC
	 * @param natAqfrDesc  the value for GW_DATA_PORTAL.WELL_REGISTRY.NAT_AQFR_DESC
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setNatAqfrDesc(String natAqfrDesc) {
		this.natAqfrDesc = natAqfrDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.LOCAL_AQUIFER_NAME
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.LOCAL_AQUIFER_NAME
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getLocalAquiferName() {
		return localAquiferName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.LOCAL_AQUIFER_NAME
	 * @param localAquiferName  the value for GW_DATA_PORTAL.WELL_REGISTRY.LOCAL_AQUIFER_NAME
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setLocalAquiferName(String localAquiferName) {
		this.localAquiferName = localAquiferName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_SN_FLAG
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.QW_SN_FLAG
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getQwSnFlag() {
		return qwSnFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_SN_FLAG
	 * @param qwSnFlag  the value for GW_DATA_PORTAL.WELL_REGISTRY.QW_SN_FLAG
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setQwSnFlag(String qwSnFlag) {
		this.qwSnFlag = qwSnFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_BASELINE_FLAG
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.QW_BASELINE_FLAG
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getQwBaselineFlag() {
		return qwBaselineFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_BASELINE_FLAG
	 * @param qwBaselineFlag  the value for GW_DATA_PORTAL.WELL_REGISTRY.QW_BASELINE_FLAG
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setQwBaselineFlag(String qwBaselineFlag) {
		this.qwBaselineFlag = qwBaselineFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_CHARS
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_CHARS
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getQwWellChars() {
		return qwWellChars;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_CHARS
	 * @param qwWellChars  the value for GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_CHARS
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setQwWellChars(String qwWellChars) {
		this.qwWellChars = qwWellChars;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_TYPE
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_TYPE
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getQwWellType() {
		return qwWellType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_TYPE
	 * @param qwWellType  the value for GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_TYPE
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setQwWellType(String qwWellType) {
		this.qwWellType = qwWellType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_SN_FLAG
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.WL_SN_FLAG
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getWlSnFlag() {
		return wlSnFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_SN_FLAG
	 * @param wlSnFlag  the value for GW_DATA_PORTAL.WELL_REGISTRY.WL_SN_FLAG
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setWlSnFlag(String wlSnFlag) {
		this.wlSnFlag = wlSnFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_BASELINE_FLAG
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.WL_BASELINE_FLAG
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getWlBaselineFlag() {
		return wlBaselineFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_BASELINE_FLAG
	 * @param wlBaselineFlag  the value for GW_DATA_PORTAL.WELL_REGISTRY.WL_BASELINE_FLAG
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setWlBaselineFlag(String wlBaselineFlag) {
		this.wlBaselineFlag = wlBaselineFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_CHARS
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_CHARS
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getWlWellChars() {
		return wlWellChars;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_CHARS
	 * @param wlWellChars  the value for GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_CHARS
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setWlWellChars(String wlWellChars) {
		this.wlWellChars = wlWellChars;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_TYPE
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_TYPE
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getWlWellType() {
		return wlWellType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_TYPE
	 * @param wlWellType  the value for GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_TYPE
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setWlWellType(String wlWellType) {
		this.wlWellType = wlWellType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.DATA_PROVIDER
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.DATA_PROVIDER
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getDataProvider() {
		return dataProvider;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.DATA_PROVIDER
	 * @param dataProvider  the value for GW_DATA_PORTAL.WELL_REGISTRY.DATA_PROVIDER
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setDataProvider(String dataProvider) {
		this.dataProvider = dataProvider;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_SYS_NAME
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.QW_SYS_NAME
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getQwSysName() {
		return qwSysName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_SYS_NAME
	 * @param qwSysName  the value for GW_DATA_PORTAL.WELL_REGISTRY.QW_SYS_NAME
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setQwSysName(String qwSysName) {
		this.qwSysName = qwSysName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_SYS_NAME
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.WL_SYS_NAME
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getWlSysName() {
		return wlSysName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_SYS_NAME
	 * @param wlSysName  the value for GW_DATA_PORTAL.WELL_REGISTRY.WL_SYS_NAME
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setWlSysName(String wlSysName) {
		this.wlSysName = wlSysName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.INSERT_DATE
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.INSERT_DATE
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public Date getInsertDate() {
		return insertDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.INSERT_DATE
	 * @param insertDate  the value for GW_DATA_PORTAL.WELL_REGISTRY.INSERT_DATE
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.MY_SITEID
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.MY_SITEID
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getMySiteid() {
		return mySiteid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.MY_SITEID
	 * @param mySiteid  the value for GW_DATA_PORTAL.WELL_REGISTRY.MY_SITEID
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setMySiteid(String mySiteid) {
		this.mySiteid = mySiteid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.DISPLAY_FLAG
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.DISPLAY_FLAG
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getDisplayFlag() {
		return displayFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.DISPLAY_FLAG
	 * @param displayFlag  the value for GW_DATA_PORTAL.WELL_REGISTRY.DISPLAY_FLAG
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setDisplayFlag(String displayFlag) {
		this.displayFlag = displayFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_DATA_PROVIDER
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.WL_DATA_PROVIDER
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getWlDataProvider() {
		return wlDataProvider;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_DATA_PROVIDER
	 * @param wlDataProvider  the value for GW_DATA_PORTAL.WELL_REGISTRY.WL_DATA_PROVIDER
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setWlDataProvider(String wlDataProvider) {
		this.wlDataProvider = wlDataProvider;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_DATA_PROVIDER
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.QW_DATA_PROVIDER
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getQwDataProvider() {
		return qwDataProvider;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_DATA_PROVIDER
	 * @param qwDataProvider  the value for GW_DATA_PORTAL.WELL_REGISTRY.QW_DATA_PROVIDER
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setQwDataProvider(String qwDataProvider) {
		this.qwDataProvider = qwDataProvider;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.LITH_DATA_PROVIDER
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.LITH_DATA_PROVIDER
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getLithDataProvider() {
		return lithDataProvider;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.LITH_DATA_PROVIDER
	 * @param lithDataProvider  the value for GW_DATA_PORTAL.WELL_REGISTRY.LITH_DATA_PROVIDER
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setLithDataProvider(String lithDataProvider) {
		this.lithDataProvider = lithDataProvider;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.CONST_DATA_PROVIDER
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.CONST_DATA_PROVIDER
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getConstDataProvider() {
		return constDataProvider;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.CONST_DATA_PROVIDER
	 * @param constDataProvider  the value for GW_DATA_PORTAL.WELL_REGISTRY.CONST_DATA_PROVIDER
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setConstDataProvider(String constDataProvider) {
		this.constDataProvider = constDataProvider;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.WELL_DEPTH
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.WELL_DEPTH
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public Float getWellDepth() {
		return wellDepth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.WELL_DEPTH
	 * @param wellDepth  the value for GW_DATA_PORTAL.WELL_REGISTRY.WELL_DEPTH
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setWellDepth(Float wellDepth) {
		this.wellDepth = wellDepth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.WELL_DEPTH_UNITS
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.WELL_DEPTH_UNITS
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getWellDepthUnits() {
		return wellDepthUnits;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.WELL_DEPTH_UNITS
	 * @param wellDepthUnits  the value for GW_DATA_PORTAL.WELL_REGISTRY.WELL_DEPTH_UNITS
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setWellDepthUnits(String wellDepthUnits) {
		this.wellDepthUnits = wellDepthUnits;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.LINK
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.LINK
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getLink() {
		return link;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.LINK
	 * @param link  the value for GW_DATA_PORTAL.WELL_REGISTRY.LINK
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setLink(String link) {
		this.link = link;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_PURPOSE
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_PURPOSE
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getWlWellPurpose() {
		return wlWellPurpose;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_PURPOSE
	 * @param wlWellPurpose  the value for GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_PURPOSE
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setWlWellPurpose(String wlWellPurpose) {
		this.wlWellPurpose = wlWellPurpose;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_PURPOSE
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_PURPOSE
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getQwWellPurpose() {
		return qwWellPurpose;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_PURPOSE
	 * @param qwWellPurpose  the value for GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_PURPOSE
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setQwWellPurpose(String qwWellPurpose) {
		this.qwWellPurpose = qwWellPurpose;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_PURPOSE_NOTES
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_PURPOSE_NOTES
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getWlWellPurposeNotes() {
		return wlWellPurposeNotes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_PURPOSE_NOTES
	 * @param wlWellPurposeNotes  the value for GW_DATA_PORTAL.WELL_REGISTRY.WL_WELL_PURPOSE_NOTES
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setWlWellPurposeNotes(String wlWellPurposeNotes) {
		this.wlWellPurposeNotes = wlWellPurposeNotes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_PURPOSE_NOTES
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_PURPOSE_NOTES
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getQwWellPurposeNotes() {
		return qwWellPurposeNotes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_PURPOSE_NOTES
	 * @param qwWellPurposeNotes  the value for GW_DATA_PORTAL.WELL_REGISTRY.QW_WELL_PURPOSE_NOTES
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setQwWellPurposeNotes(String qwWellPurposeNotes) {
		this.qwWellPurposeNotes = qwWellPurposeNotes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.STATE_CD
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.STATE_CD
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public Integer getStateCd() {
		return stateCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.STATE_CD
	 * @param stateCd  the value for GW_DATA_PORTAL.WELL_REGISTRY.STATE_CD
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setStateCd(Integer stateCd) {
		this.stateCd = stateCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.COUNTY_CD
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.COUNTY_CD
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public Integer getCountyCd() {
		return countyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.COUNTY_CD
	 * @param countyCd  the value for GW_DATA_PORTAL.WELL_REGISTRY.COUNTY_CD
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setCountyCd(Integer countyCd) {
		this.countyCd = countyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.UPDATE_DATE
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.UPDATE_DATE
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.UPDATE_DATE
	 * @param updateDate  the value for GW_DATA_PORTAL.WELL_REGISTRY.UPDATE_DATE
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.ALT_UNITS
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.ALT_UNITS
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public Integer getAltUnits() {
		return altUnits;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.ALT_UNITS
	 * @param altUnits  the value for GW_DATA_PORTAL.WELL_REGISTRY.ALT_UNITS
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setAltUnits(Integer altUnits) {
		this.altUnits = altUnits;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.LOCAL_AQUIFER_CD
	 * @return  the value of GW_DATA_PORTAL.WELL_REGISTRY.LOCAL_AQUIFER_CD
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public String getLocalAquiferCd() {
		return localAquiferCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GW_DATA_PORTAL.WELL_REGISTRY.LOCAL_AQUIFER_CD
	 * @param localAquiferCd  the value for GW_DATA_PORTAL.WELL_REGISTRY.LOCAL_AQUIFER_CD
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	public void setLocalAquiferCd(String localAquiferCd) {
		this.localAquiferCd = localAquiferCd;
	}
}