package gov.usgs.ngwmn.dm.dao;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WellRegistryExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table GW_DATA_PORTAL.WELL_REGISTRY
	 * @mbggenerated  Wed Apr 11 16:58:46 CDT 2012
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table GW_DATA_PORTAL.WELL_REGISTRY
	 * @mbggenerated  Wed Apr 11 16:58:46 CDT 2012
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table GW_DATA_PORTAL.WELL_REGISTRY
	 * @mbggenerated  Wed Apr 11 16:58:46 CDT 2012
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.WELL_REGISTRY
	 * @mbggenerated  Wed Apr 11 16:58:46 CDT 2012
	 */
	public WellRegistryExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.WELL_REGISTRY
	 * @mbggenerated  Wed Apr 11 16:58:46 CDT 2012
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.WELL_REGISTRY
	 * @mbggenerated  Wed Apr 11 16:58:46 CDT 2012
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.WELL_REGISTRY
	 * @mbggenerated  Wed Apr 11 16:58:46 CDT 2012
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.WELL_REGISTRY
	 * @mbggenerated  Wed Apr 11 16:58:46 CDT 2012
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.WELL_REGISTRY
	 * @mbggenerated  Wed Apr 11 16:58:46 CDT 2012
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.WELL_REGISTRY
	 * @mbggenerated  Wed Apr 11 16:58:46 CDT 2012
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.WELL_REGISTRY
	 * @mbggenerated  Wed Apr 11 16:58:46 CDT 2012
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.WELL_REGISTRY
	 * @mbggenerated  Wed Apr 11 16:58:46 CDT 2012
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.WELL_REGISTRY
	 * @mbggenerated  Wed Apr 11 16:58:46 CDT 2012
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.WELL_REGISTRY
	 * @mbggenerated  Wed Apr 11 16:58:46 CDT 2012
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table GW_DATA_PORTAL.WELL_REGISTRY
	 * @mbggenerated  Wed Apr 11 16:58:46 CDT 2012
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andAgencyCdIsNull() {
			addCriterion("AGENCY_CD is null");
			return (Criteria) this;
		}

		public Criteria andAgencyCdIsNotNull() {
			addCriterion("AGENCY_CD is not null");
			return (Criteria) this;
		}

		public Criteria andAgencyCdEqualTo(String value) {
			addCriterion("AGENCY_CD =", value, "agencyCd");
			return (Criteria) this;
		}

		public Criteria andAgencyCdNotEqualTo(String value) {
			addCriterion("AGENCY_CD <>", value, "agencyCd");
			return (Criteria) this;
		}

		public Criteria andAgencyCdGreaterThan(String value) {
			addCriterion("AGENCY_CD >", value, "agencyCd");
			return (Criteria) this;
		}

		public Criteria andAgencyCdGreaterThanOrEqualTo(String value) {
			addCriterion("AGENCY_CD >=", value, "agencyCd");
			return (Criteria) this;
		}

		public Criteria andAgencyCdLessThan(String value) {
			addCriterion("AGENCY_CD <", value, "agencyCd");
			return (Criteria) this;
		}

		public Criteria andAgencyCdLessThanOrEqualTo(String value) {
			addCriterion("AGENCY_CD <=", value, "agencyCd");
			return (Criteria) this;
		}

		public Criteria andAgencyCdLike(String value) {
			addCriterion("AGENCY_CD like", value, "agencyCd");
			return (Criteria) this;
		}

		public Criteria andAgencyCdNotLike(String value) {
			addCriterion("AGENCY_CD not like", value, "agencyCd");
			return (Criteria) this;
		}

		public Criteria andAgencyCdIn(List<String> values) {
			addCriterion("AGENCY_CD in", values, "agencyCd");
			return (Criteria) this;
		}

		public Criteria andAgencyCdNotIn(List<String> values) {
			addCriterion("AGENCY_CD not in", values, "agencyCd");
			return (Criteria) this;
		}

		public Criteria andAgencyCdBetween(String value1, String value2) {
			addCriterion("AGENCY_CD between", value1, value2, "agencyCd");
			return (Criteria) this;
		}

		public Criteria andAgencyCdNotBetween(String value1, String value2) {
			addCriterion("AGENCY_CD not between", value1, value2, "agencyCd");
			return (Criteria) this;
		}

		public Criteria andSiteNoIsNull() {
			addCriterion("SITE_NO is null");
			return (Criteria) this;
		}

		public Criteria andSiteNoIsNotNull() {
			addCriterion("SITE_NO is not null");
			return (Criteria) this;
		}

		public Criteria andSiteNoEqualTo(String value) {
			addCriterion("SITE_NO =", value, "siteNo");
			return (Criteria) this;
		}

		public Criteria andSiteNoNotEqualTo(String value) {
			addCriterion("SITE_NO <>", value, "siteNo");
			return (Criteria) this;
		}

		public Criteria andSiteNoGreaterThan(String value) {
			addCriterion("SITE_NO >", value, "siteNo");
			return (Criteria) this;
		}

		public Criteria andSiteNoGreaterThanOrEqualTo(String value) {
			addCriterion("SITE_NO >=", value, "siteNo");
			return (Criteria) this;
		}

		public Criteria andSiteNoLessThan(String value) {
			addCriterion("SITE_NO <", value, "siteNo");
			return (Criteria) this;
		}

		public Criteria andSiteNoLessThanOrEqualTo(String value) {
			addCriterion("SITE_NO <=", value, "siteNo");
			return (Criteria) this;
		}

		public Criteria andSiteNoLike(String value) {
			addCriterion("SITE_NO like", value, "siteNo");
			return (Criteria) this;
		}

		public Criteria andSiteNoNotLike(String value) {
			addCriterion("SITE_NO not like", value, "siteNo");
			return (Criteria) this;
		}

		public Criteria andSiteNoIn(List<String> values) {
			addCriterion("SITE_NO in", values, "siteNo");
			return (Criteria) this;
		}

		public Criteria andSiteNoNotIn(List<String> values) {
			addCriterion("SITE_NO not in", values, "siteNo");
			return (Criteria) this;
		}

		public Criteria andSiteNoBetween(String value1, String value2) {
			addCriterion("SITE_NO between", value1, value2, "siteNo");
			return (Criteria) this;
		}

		public Criteria andSiteNoNotBetween(String value1, String value2) {
			addCriterion("SITE_NO not between", value1, value2, "siteNo");
			return (Criteria) this;
		}

		public Criteria andAgencyNmIsNull() {
			addCriterion("AGENCY_NM is null");
			return (Criteria) this;
		}

		public Criteria andAgencyNmIsNotNull() {
			addCriterion("AGENCY_NM is not null");
			return (Criteria) this;
		}

		public Criteria andAgencyNmEqualTo(String value) {
			addCriterion("AGENCY_NM =", value, "agencyNm");
			return (Criteria) this;
		}

		public Criteria andAgencyNmNotEqualTo(String value) {
			addCriterion("AGENCY_NM <>", value, "agencyNm");
			return (Criteria) this;
		}

		public Criteria andAgencyNmGreaterThan(String value) {
			addCriterion("AGENCY_NM >", value, "agencyNm");
			return (Criteria) this;
		}

		public Criteria andAgencyNmGreaterThanOrEqualTo(String value) {
			addCriterion("AGENCY_NM >=", value, "agencyNm");
			return (Criteria) this;
		}

		public Criteria andAgencyNmLessThan(String value) {
			addCriterion("AGENCY_NM <", value, "agencyNm");
			return (Criteria) this;
		}

		public Criteria andAgencyNmLessThanOrEqualTo(String value) {
			addCriterion("AGENCY_NM <=", value, "agencyNm");
			return (Criteria) this;
		}

		public Criteria andAgencyNmLike(String value) {
			addCriterion("AGENCY_NM like", value, "agencyNm");
			return (Criteria) this;
		}

		public Criteria andAgencyNmNotLike(String value) {
			addCriterion("AGENCY_NM not like", value, "agencyNm");
			return (Criteria) this;
		}

		public Criteria andAgencyNmIn(List<String> values) {
			addCriterion("AGENCY_NM in", values, "agencyNm");
			return (Criteria) this;
		}

		public Criteria andAgencyNmNotIn(List<String> values) {
			addCriterion("AGENCY_NM not in", values, "agencyNm");
			return (Criteria) this;
		}

		public Criteria andAgencyNmBetween(String value1, String value2) {
			addCriterion("AGENCY_NM between", value1, value2, "agencyNm");
			return (Criteria) this;
		}

		public Criteria andAgencyNmNotBetween(String value1, String value2) {
			addCriterion("AGENCY_NM not between", value1, value2, "agencyNm");
			return (Criteria) this;
		}

		public Criteria andAgencyMedIsNull() {
			addCriterion("AGENCY_MED is null");
			return (Criteria) this;
		}

		public Criteria andAgencyMedIsNotNull() {
			addCriterion("AGENCY_MED is not null");
			return (Criteria) this;
		}

		public Criteria andAgencyMedEqualTo(String value) {
			addCriterion("AGENCY_MED =", value, "agencyMed");
			return (Criteria) this;
		}

		public Criteria andAgencyMedNotEqualTo(String value) {
			addCriterion("AGENCY_MED <>", value, "agencyMed");
			return (Criteria) this;
		}

		public Criteria andAgencyMedGreaterThan(String value) {
			addCriterion("AGENCY_MED >", value, "agencyMed");
			return (Criteria) this;
		}

		public Criteria andAgencyMedGreaterThanOrEqualTo(String value) {
			addCriterion("AGENCY_MED >=", value, "agencyMed");
			return (Criteria) this;
		}

		public Criteria andAgencyMedLessThan(String value) {
			addCriterion("AGENCY_MED <", value, "agencyMed");
			return (Criteria) this;
		}

		public Criteria andAgencyMedLessThanOrEqualTo(String value) {
			addCriterion("AGENCY_MED <=", value, "agencyMed");
			return (Criteria) this;
		}

		public Criteria andAgencyMedLike(String value) {
			addCriterion("AGENCY_MED like", value, "agencyMed");
			return (Criteria) this;
		}

		public Criteria andAgencyMedNotLike(String value) {
			addCriterion("AGENCY_MED not like", value, "agencyMed");
			return (Criteria) this;
		}

		public Criteria andAgencyMedIn(List<String> values) {
			addCriterion("AGENCY_MED in", values, "agencyMed");
			return (Criteria) this;
		}

		public Criteria andAgencyMedNotIn(List<String> values) {
			addCriterion("AGENCY_MED not in", values, "agencyMed");
			return (Criteria) this;
		}

		public Criteria andAgencyMedBetween(String value1, String value2) {
			addCriterion("AGENCY_MED between", value1, value2, "agencyMed");
			return (Criteria) this;
		}

		public Criteria andAgencyMedNotBetween(String value1, String value2) {
			addCriterion("AGENCY_MED not between", value1, value2, "agencyMed");
			return (Criteria) this;
		}

		public Criteria andSiteNameIsNull() {
			addCriterion("SITE_NAME is null");
			return (Criteria) this;
		}

		public Criteria andSiteNameIsNotNull() {
			addCriterion("SITE_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andSiteNameEqualTo(String value) {
			addCriterion("SITE_NAME =", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameNotEqualTo(String value) {
			addCriterion("SITE_NAME <>", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameGreaterThan(String value) {
			addCriterion("SITE_NAME >", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameGreaterThanOrEqualTo(String value) {
			addCriterion("SITE_NAME >=", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameLessThan(String value) {
			addCriterion("SITE_NAME <", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameLessThanOrEqualTo(String value) {
			addCriterion("SITE_NAME <=", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameLike(String value) {
			addCriterion("SITE_NAME like", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameNotLike(String value) {
			addCriterion("SITE_NAME not like", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameIn(List<String> values) {
			addCriterion("SITE_NAME in", values, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameNotIn(List<String> values) {
			addCriterion("SITE_NAME not in", values, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameBetween(String value1, String value2) {
			addCriterion("SITE_NAME between", value1, value2, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameNotBetween(String value1, String value2) {
			addCriterion("SITE_NAME not between", value1, value2, "siteName");
			return (Criteria) this;
		}

		public Criteria andDecLatVaIsNull() {
			addCriterion("DEC_LAT_VA is null");
			return (Criteria) this;
		}

		public Criteria andDecLatVaIsNotNull() {
			addCriterion("DEC_LAT_VA is not null");
			return (Criteria) this;
		}

		public Criteria andDecLatVaEqualTo(Double value) {
			addCriterion("DEC_LAT_VA =", value, "decLatVa");
			return (Criteria) this;
		}

		public Criteria andDecLatVaNotEqualTo(Double value) {
			addCriterion("DEC_LAT_VA <>", value, "decLatVa");
			return (Criteria) this;
		}

		public Criteria andDecLatVaGreaterThan(Double value) {
			addCriterion("DEC_LAT_VA >", value, "decLatVa");
			return (Criteria) this;
		}

		public Criteria andDecLatVaGreaterThanOrEqualTo(Double value) {
			addCriterion("DEC_LAT_VA >=", value, "decLatVa");
			return (Criteria) this;
		}

		public Criteria andDecLatVaLessThan(Double value) {
			addCriterion("DEC_LAT_VA <", value, "decLatVa");
			return (Criteria) this;
		}

		public Criteria andDecLatVaLessThanOrEqualTo(Double value) {
			addCriterion("DEC_LAT_VA <=", value, "decLatVa");
			return (Criteria) this;
		}

		public Criteria andDecLatVaIn(List<Double> values) {
			addCriterion("DEC_LAT_VA in", values, "decLatVa");
			return (Criteria) this;
		}

		public Criteria andDecLatVaNotIn(List<Double> values) {
			addCriterion("DEC_LAT_VA not in", values, "decLatVa");
			return (Criteria) this;
		}

		public Criteria andDecLatVaBetween(Double value1, Double value2) {
			addCriterion("DEC_LAT_VA between", value1, value2, "decLatVa");
			return (Criteria) this;
		}

		public Criteria andDecLatVaNotBetween(Double value1, Double value2) {
			addCriterion("DEC_LAT_VA not between", value1, value2, "decLatVa");
			return (Criteria) this;
		}

		public Criteria andDecLongVaIsNull() {
			addCriterion("DEC_LONG_VA is null");
			return (Criteria) this;
		}

		public Criteria andDecLongVaIsNotNull() {
			addCriterion("DEC_LONG_VA is not null");
			return (Criteria) this;
		}

		public Criteria andDecLongVaEqualTo(Double value) {
			addCriterion("DEC_LONG_VA =", value, "decLongVa");
			return (Criteria) this;
		}

		public Criteria andDecLongVaNotEqualTo(Double value) {
			addCriterion("DEC_LONG_VA <>", value, "decLongVa");
			return (Criteria) this;
		}

		public Criteria andDecLongVaGreaterThan(Double value) {
			addCriterion("DEC_LONG_VA >", value, "decLongVa");
			return (Criteria) this;
		}

		public Criteria andDecLongVaGreaterThanOrEqualTo(Double value) {
			addCriterion("DEC_LONG_VA >=", value, "decLongVa");
			return (Criteria) this;
		}

		public Criteria andDecLongVaLessThan(Double value) {
			addCriterion("DEC_LONG_VA <", value, "decLongVa");
			return (Criteria) this;
		}

		public Criteria andDecLongVaLessThanOrEqualTo(Double value) {
			addCriterion("DEC_LONG_VA <=", value, "decLongVa");
			return (Criteria) this;
		}

		public Criteria andDecLongVaIn(List<Double> values) {
			addCriterion("DEC_LONG_VA in", values, "decLongVa");
			return (Criteria) this;
		}

		public Criteria andDecLongVaNotIn(List<Double> values) {
			addCriterion("DEC_LONG_VA not in", values, "decLongVa");
			return (Criteria) this;
		}

		public Criteria andDecLongVaBetween(Double value1, Double value2) {
			addCriterion("DEC_LONG_VA between", value1, value2, "decLongVa");
			return (Criteria) this;
		}

		public Criteria andDecLongVaNotBetween(Double value1, Double value2) {
			addCriterion("DEC_LONG_VA not between", value1, value2, "decLongVa");
			return (Criteria) this;
		}

		public Criteria andHorzDatumIsNull() {
			addCriterion("HORZ_DATUM is null");
			return (Criteria) this;
		}

		public Criteria andHorzDatumIsNotNull() {
			addCriterion("HORZ_DATUM is not null");
			return (Criteria) this;
		}

		public Criteria andHorzDatumEqualTo(String value) {
			addCriterion("HORZ_DATUM =", value, "horzDatum");
			return (Criteria) this;
		}

		public Criteria andHorzDatumNotEqualTo(String value) {
			addCriterion("HORZ_DATUM <>", value, "horzDatum");
			return (Criteria) this;
		}

		public Criteria andHorzDatumGreaterThan(String value) {
			addCriterion("HORZ_DATUM >", value, "horzDatum");
			return (Criteria) this;
		}

		public Criteria andHorzDatumGreaterThanOrEqualTo(String value) {
			addCriterion("HORZ_DATUM >=", value, "horzDatum");
			return (Criteria) this;
		}

		public Criteria andHorzDatumLessThan(String value) {
			addCriterion("HORZ_DATUM <", value, "horzDatum");
			return (Criteria) this;
		}

		public Criteria andHorzDatumLessThanOrEqualTo(String value) {
			addCriterion("HORZ_DATUM <=", value, "horzDatum");
			return (Criteria) this;
		}

		public Criteria andHorzDatumLike(String value) {
			addCriterion("HORZ_DATUM like", value, "horzDatum");
			return (Criteria) this;
		}

		public Criteria andHorzDatumNotLike(String value) {
			addCriterion("HORZ_DATUM not like", value, "horzDatum");
			return (Criteria) this;
		}

		public Criteria andHorzDatumIn(List<String> values) {
			addCriterion("HORZ_DATUM in", values, "horzDatum");
			return (Criteria) this;
		}

		public Criteria andHorzDatumNotIn(List<String> values) {
			addCriterion("HORZ_DATUM not in", values, "horzDatum");
			return (Criteria) this;
		}

		public Criteria andHorzDatumBetween(String value1, String value2) {
			addCriterion("HORZ_DATUM between", value1, value2, "horzDatum");
			return (Criteria) this;
		}

		public Criteria andHorzDatumNotBetween(String value1, String value2) {
			addCriterion("HORZ_DATUM not between", value1, value2, "horzDatum");
			return (Criteria) this;
		}

		public Criteria andAltVaIsNull() {
			addCriterion("ALT_VA is null");
			return (Criteria) this;
		}

		public Criteria andAltVaIsNotNull() {
			addCriterion("ALT_VA is not null");
			return (Criteria) this;
		}

		public Criteria andAltVaEqualTo(Double value) {
			addCriterion("ALT_VA =", value, "altVa");
			return (Criteria) this;
		}

		public Criteria andAltVaNotEqualTo(Double value) {
			addCriterion("ALT_VA <>", value, "altVa");
			return (Criteria) this;
		}

		public Criteria andAltVaGreaterThan(Double value) {
			addCriterion("ALT_VA >", value, "altVa");
			return (Criteria) this;
		}

		public Criteria andAltVaGreaterThanOrEqualTo(Double value) {
			addCriterion("ALT_VA >=", value, "altVa");
			return (Criteria) this;
		}

		public Criteria andAltVaLessThan(Double value) {
			addCriterion("ALT_VA <", value, "altVa");
			return (Criteria) this;
		}

		public Criteria andAltVaLessThanOrEqualTo(Double value) {
			addCriterion("ALT_VA <=", value, "altVa");
			return (Criteria) this;
		}

		public Criteria andAltVaIn(List<Double> values) {
			addCriterion("ALT_VA in", values, "altVa");
			return (Criteria) this;
		}

		public Criteria andAltVaNotIn(List<Double> values) {
			addCriterion("ALT_VA not in", values, "altVa");
			return (Criteria) this;
		}

		public Criteria andAltVaBetween(Double value1, Double value2) {
			addCriterion("ALT_VA between", value1, value2, "altVa");
			return (Criteria) this;
		}

		public Criteria andAltVaNotBetween(Double value1, Double value2) {
			addCriterion("ALT_VA not between", value1, value2, "altVa");
			return (Criteria) this;
		}

		public Criteria andAltDatumCdIsNull() {
			addCriterion("ALT_DATUM_CD is null");
			return (Criteria) this;
		}

		public Criteria andAltDatumCdIsNotNull() {
			addCriterion("ALT_DATUM_CD is not null");
			return (Criteria) this;
		}

		public Criteria andAltDatumCdEqualTo(String value) {
			addCriterion("ALT_DATUM_CD =", value, "altDatumCd");
			return (Criteria) this;
		}

		public Criteria andAltDatumCdNotEqualTo(String value) {
			addCriterion("ALT_DATUM_CD <>", value, "altDatumCd");
			return (Criteria) this;
		}

		public Criteria andAltDatumCdGreaterThan(String value) {
			addCriterion("ALT_DATUM_CD >", value, "altDatumCd");
			return (Criteria) this;
		}

		public Criteria andAltDatumCdGreaterThanOrEqualTo(String value) {
			addCriterion("ALT_DATUM_CD >=", value, "altDatumCd");
			return (Criteria) this;
		}

		public Criteria andAltDatumCdLessThan(String value) {
			addCriterion("ALT_DATUM_CD <", value, "altDatumCd");
			return (Criteria) this;
		}

		public Criteria andAltDatumCdLessThanOrEqualTo(String value) {
			addCriterion("ALT_DATUM_CD <=", value, "altDatumCd");
			return (Criteria) this;
		}

		public Criteria andAltDatumCdLike(String value) {
			addCriterion("ALT_DATUM_CD like", value, "altDatumCd");
			return (Criteria) this;
		}

		public Criteria andAltDatumCdNotLike(String value) {
			addCriterion("ALT_DATUM_CD not like", value, "altDatumCd");
			return (Criteria) this;
		}

		public Criteria andAltDatumCdIn(List<String> values) {
			addCriterion("ALT_DATUM_CD in", values, "altDatumCd");
			return (Criteria) this;
		}

		public Criteria andAltDatumCdNotIn(List<String> values) {
			addCriterion("ALT_DATUM_CD not in", values, "altDatumCd");
			return (Criteria) this;
		}

		public Criteria andAltDatumCdBetween(String value1, String value2) {
			addCriterion("ALT_DATUM_CD between", value1, value2, "altDatumCd");
			return (Criteria) this;
		}

		public Criteria andAltDatumCdNotBetween(String value1, String value2) {
			addCriterion("ALT_DATUM_CD not between", value1, value2,
					"altDatumCd");
			return (Criteria) this;
		}

		public Criteria andNatAquiferCdIsNull() {
			addCriterion("NAT_AQUIFER_CD is null");
			return (Criteria) this;
		}

		public Criteria andNatAquiferCdIsNotNull() {
			addCriterion("NAT_AQUIFER_CD is not null");
			return (Criteria) this;
		}

		public Criteria andNatAquiferCdEqualTo(String value) {
			addCriterion("NAT_AQUIFER_CD =", value, "natAquiferCd");
			return (Criteria) this;
		}

		public Criteria andNatAquiferCdNotEqualTo(String value) {
			addCriterion("NAT_AQUIFER_CD <>", value, "natAquiferCd");
			return (Criteria) this;
		}

		public Criteria andNatAquiferCdGreaterThan(String value) {
			addCriterion("NAT_AQUIFER_CD >", value, "natAquiferCd");
			return (Criteria) this;
		}

		public Criteria andNatAquiferCdGreaterThanOrEqualTo(String value) {
			addCriterion("NAT_AQUIFER_CD >=", value, "natAquiferCd");
			return (Criteria) this;
		}

		public Criteria andNatAquiferCdLessThan(String value) {
			addCriterion("NAT_AQUIFER_CD <", value, "natAquiferCd");
			return (Criteria) this;
		}

		public Criteria andNatAquiferCdLessThanOrEqualTo(String value) {
			addCriterion("NAT_AQUIFER_CD <=", value, "natAquiferCd");
			return (Criteria) this;
		}

		public Criteria andNatAquiferCdLike(String value) {
			addCriterion("NAT_AQUIFER_CD like", value, "natAquiferCd");
			return (Criteria) this;
		}

		public Criteria andNatAquiferCdNotLike(String value) {
			addCriterion("NAT_AQUIFER_CD not like", value, "natAquiferCd");
			return (Criteria) this;
		}

		public Criteria andNatAquiferCdIn(List<String> values) {
			addCriterion("NAT_AQUIFER_CD in", values, "natAquiferCd");
			return (Criteria) this;
		}

		public Criteria andNatAquiferCdNotIn(List<String> values) {
			addCriterion("NAT_AQUIFER_CD not in", values, "natAquiferCd");
			return (Criteria) this;
		}

		public Criteria andNatAquiferCdBetween(String value1, String value2) {
			addCriterion("NAT_AQUIFER_CD between", value1, value2,
					"natAquiferCd");
			return (Criteria) this;
		}

		public Criteria andNatAquiferCdNotBetween(String value1, String value2) {
			addCriterion("NAT_AQUIFER_CD not between", value1, value2,
					"natAquiferCd");
			return (Criteria) this;
		}

		public Criteria andNatAqfrDescIsNull() {
			addCriterion("NAT_AQFR_DESC is null");
			return (Criteria) this;
		}

		public Criteria andNatAqfrDescIsNotNull() {
			addCriterion("NAT_AQFR_DESC is not null");
			return (Criteria) this;
		}

		public Criteria andNatAqfrDescEqualTo(String value) {
			addCriterion("NAT_AQFR_DESC =", value, "natAqfrDesc");
			return (Criteria) this;
		}

		public Criteria andNatAqfrDescNotEqualTo(String value) {
			addCriterion("NAT_AQFR_DESC <>", value, "natAqfrDesc");
			return (Criteria) this;
		}

		public Criteria andNatAqfrDescGreaterThan(String value) {
			addCriterion("NAT_AQFR_DESC >", value, "natAqfrDesc");
			return (Criteria) this;
		}

		public Criteria andNatAqfrDescGreaterThanOrEqualTo(String value) {
			addCriterion("NAT_AQFR_DESC >=", value, "natAqfrDesc");
			return (Criteria) this;
		}

		public Criteria andNatAqfrDescLessThan(String value) {
			addCriterion("NAT_AQFR_DESC <", value, "natAqfrDesc");
			return (Criteria) this;
		}

		public Criteria andNatAqfrDescLessThanOrEqualTo(String value) {
			addCriterion("NAT_AQFR_DESC <=", value, "natAqfrDesc");
			return (Criteria) this;
		}

		public Criteria andNatAqfrDescLike(String value) {
			addCriterion("NAT_AQFR_DESC like", value, "natAqfrDesc");
			return (Criteria) this;
		}

		public Criteria andNatAqfrDescNotLike(String value) {
			addCriterion("NAT_AQFR_DESC not like", value, "natAqfrDesc");
			return (Criteria) this;
		}

		public Criteria andNatAqfrDescIn(List<String> values) {
			addCriterion("NAT_AQFR_DESC in", values, "natAqfrDesc");
			return (Criteria) this;
		}

		public Criteria andNatAqfrDescNotIn(List<String> values) {
			addCriterion("NAT_AQFR_DESC not in", values, "natAqfrDesc");
			return (Criteria) this;
		}

		public Criteria andNatAqfrDescBetween(String value1, String value2) {
			addCriterion("NAT_AQFR_DESC between", value1, value2, "natAqfrDesc");
			return (Criteria) this;
		}

		public Criteria andNatAqfrDescNotBetween(String value1, String value2) {
			addCriterion("NAT_AQFR_DESC not between", value1, value2,
					"natAqfrDesc");
			return (Criteria) this;
		}

		public Criteria andLocalAquiferNameIsNull() {
			addCriterion("LOCAL_AQUIFER_NAME is null");
			return (Criteria) this;
		}

		public Criteria andLocalAquiferNameIsNotNull() {
			addCriterion("LOCAL_AQUIFER_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andLocalAquiferNameEqualTo(String value) {
			addCriterion("LOCAL_AQUIFER_NAME =", value, "localAquiferName");
			return (Criteria) this;
		}

		public Criteria andLocalAquiferNameNotEqualTo(String value) {
			addCriterion("LOCAL_AQUIFER_NAME <>", value, "localAquiferName");
			return (Criteria) this;
		}

		public Criteria andLocalAquiferNameGreaterThan(String value) {
			addCriterion("LOCAL_AQUIFER_NAME >", value, "localAquiferName");
			return (Criteria) this;
		}

		public Criteria andLocalAquiferNameGreaterThanOrEqualTo(String value) {
			addCriterion("LOCAL_AQUIFER_NAME >=", value, "localAquiferName");
			return (Criteria) this;
		}

		public Criteria andLocalAquiferNameLessThan(String value) {
			addCriterion("LOCAL_AQUIFER_NAME <", value, "localAquiferName");
			return (Criteria) this;
		}

		public Criteria andLocalAquiferNameLessThanOrEqualTo(String value) {
			addCriterion("LOCAL_AQUIFER_NAME <=", value, "localAquiferName");
			return (Criteria) this;
		}

		public Criteria andLocalAquiferNameLike(String value) {
			addCriterion("LOCAL_AQUIFER_NAME like", value, "localAquiferName");
			return (Criteria) this;
		}

		public Criteria andLocalAquiferNameNotLike(String value) {
			addCriterion("LOCAL_AQUIFER_NAME not like", value,
					"localAquiferName");
			return (Criteria) this;
		}

		public Criteria andLocalAquiferNameIn(List<String> values) {
			addCriterion("LOCAL_AQUIFER_NAME in", values, "localAquiferName");
			return (Criteria) this;
		}

		public Criteria andLocalAquiferNameNotIn(List<String> values) {
			addCriterion("LOCAL_AQUIFER_NAME not in", values,
					"localAquiferName");
			return (Criteria) this;
		}

		public Criteria andLocalAquiferNameBetween(String value1, String value2) {
			addCriterion("LOCAL_AQUIFER_NAME between", value1, value2,
					"localAquiferName");
			return (Criteria) this;
		}

		public Criteria andLocalAquiferNameNotBetween(String value1,
				String value2) {
			addCriterion("LOCAL_AQUIFER_NAME not between", value1, value2,
					"localAquiferName");
			return (Criteria) this;
		}

		public Criteria andQwSnFlagIsNull() {
			addCriterion("QW_SN_FLAG is null");
			return (Criteria) this;
		}

		public Criteria andQwSnFlagIsNotNull() {
			addCriterion("QW_SN_FLAG is not null");
			return (Criteria) this;
		}

		public Criteria andQwSnFlagEqualTo(String value) {
			addCriterion("QW_SN_FLAG =", value, "qwSnFlag");
			return (Criteria) this;
		}

		public Criteria andQwSnFlagNotEqualTo(String value) {
			addCriterion("QW_SN_FLAG <>", value, "qwSnFlag");
			return (Criteria) this;
		}

		public Criteria andQwSnFlagGreaterThan(String value) {
			addCriterion("QW_SN_FLAG >", value, "qwSnFlag");
			return (Criteria) this;
		}

		public Criteria andQwSnFlagGreaterThanOrEqualTo(String value) {
			addCriterion("QW_SN_FLAG >=", value, "qwSnFlag");
			return (Criteria) this;
		}

		public Criteria andQwSnFlagLessThan(String value) {
			addCriterion("QW_SN_FLAG <", value, "qwSnFlag");
			return (Criteria) this;
		}

		public Criteria andQwSnFlagLessThanOrEqualTo(String value) {
			addCriterion("QW_SN_FLAG <=", value, "qwSnFlag");
			return (Criteria) this;
		}

		public Criteria andQwSnFlagLike(String value) {
			addCriterion("QW_SN_FLAG like", value, "qwSnFlag");
			return (Criteria) this;
		}

		public Criteria andQwSnFlagNotLike(String value) {
			addCriterion("QW_SN_FLAG not like", value, "qwSnFlag");
			return (Criteria) this;
		}

		public Criteria andQwSnFlagIn(List<String> values) {
			addCriterion("QW_SN_FLAG in", values, "qwSnFlag");
			return (Criteria) this;
		}

		public Criteria andQwSnFlagNotIn(List<String> values) {
			addCriterion("QW_SN_FLAG not in", values, "qwSnFlag");
			return (Criteria) this;
		}

		public Criteria andQwSnFlagBetween(String value1, String value2) {
			addCriterion("QW_SN_FLAG between", value1, value2, "qwSnFlag");
			return (Criteria) this;
		}

		public Criteria andQwSnFlagNotBetween(String value1, String value2) {
			addCriterion("QW_SN_FLAG not between", value1, value2, "qwSnFlag");
			return (Criteria) this;
		}

		public Criteria andQwBaselineFlagIsNull() {
			addCriterion("QW_BASELINE_FLAG is null");
			return (Criteria) this;
		}

		public Criteria andQwBaselineFlagIsNotNull() {
			addCriterion("QW_BASELINE_FLAG is not null");
			return (Criteria) this;
		}

		public Criteria andQwBaselineFlagEqualTo(String value) {
			addCriterion("QW_BASELINE_FLAG =", value, "qwBaselineFlag");
			return (Criteria) this;
		}

		public Criteria andQwBaselineFlagNotEqualTo(String value) {
			addCriterion("QW_BASELINE_FLAG <>", value, "qwBaselineFlag");
			return (Criteria) this;
		}

		public Criteria andQwBaselineFlagGreaterThan(String value) {
			addCriterion("QW_BASELINE_FLAG >", value, "qwBaselineFlag");
			return (Criteria) this;
		}

		public Criteria andQwBaselineFlagGreaterThanOrEqualTo(String value) {
			addCriterion("QW_BASELINE_FLAG >=", value, "qwBaselineFlag");
			return (Criteria) this;
		}

		public Criteria andQwBaselineFlagLessThan(String value) {
			addCriterion("QW_BASELINE_FLAG <", value, "qwBaselineFlag");
			return (Criteria) this;
		}

		public Criteria andQwBaselineFlagLessThanOrEqualTo(String value) {
			addCriterion("QW_BASELINE_FLAG <=", value, "qwBaselineFlag");
			return (Criteria) this;
		}

		public Criteria andQwBaselineFlagLike(String value) {
			addCriterion("QW_BASELINE_FLAG like", value, "qwBaselineFlag");
			return (Criteria) this;
		}

		public Criteria andQwBaselineFlagNotLike(String value) {
			addCriterion("QW_BASELINE_FLAG not like", value, "qwBaselineFlag");
			return (Criteria) this;
		}

		public Criteria andQwBaselineFlagIn(List<String> values) {
			addCriterion("QW_BASELINE_FLAG in", values, "qwBaselineFlag");
			return (Criteria) this;
		}

		public Criteria andQwBaselineFlagNotIn(List<String> values) {
			addCriterion("QW_BASELINE_FLAG not in", values, "qwBaselineFlag");
			return (Criteria) this;
		}

		public Criteria andQwBaselineFlagBetween(String value1, String value2) {
			addCriterion("QW_BASELINE_FLAG between", value1, value2,
					"qwBaselineFlag");
			return (Criteria) this;
		}

		public Criteria andQwBaselineFlagNotBetween(String value1, String value2) {
			addCriterion("QW_BASELINE_FLAG not between", value1, value2,
					"qwBaselineFlag");
			return (Criteria) this;
		}

		public Criteria andQwWellCharsIsNull() {
			addCriterion("QW_WELL_CHARS is null");
			return (Criteria) this;
		}

		public Criteria andQwWellCharsIsNotNull() {
			addCriterion("QW_WELL_CHARS is not null");
			return (Criteria) this;
		}

		public Criteria andQwWellCharsEqualTo(String value) {
			addCriterion("QW_WELL_CHARS =", value, "qwWellChars");
			return (Criteria) this;
		}

		public Criteria andQwWellCharsNotEqualTo(String value) {
			addCriterion("QW_WELL_CHARS <>", value, "qwWellChars");
			return (Criteria) this;
		}

		public Criteria andQwWellCharsGreaterThan(String value) {
			addCriterion("QW_WELL_CHARS >", value, "qwWellChars");
			return (Criteria) this;
		}

		public Criteria andQwWellCharsGreaterThanOrEqualTo(String value) {
			addCriterion("QW_WELL_CHARS >=", value, "qwWellChars");
			return (Criteria) this;
		}

		public Criteria andQwWellCharsLessThan(String value) {
			addCriterion("QW_WELL_CHARS <", value, "qwWellChars");
			return (Criteria) this;
		}

		public Criteria andQwWellCharsLessThanOrEqualTo(String value) {
			addCriterion("QW_WELL_CHARS <=", value, "qwWellChars");
			return (Criteria) this;
		}

		public Criteria andQwWellCharsLike(String value) {
			addCriterion("QW_WELL_CHARS like", value, "qwWellChars");
			return (Criteria) this;
		}

		public Criteria andQwWellCharsNotLike(String value) {
			addCriterion("QW_WELL_CHARS not like", value, "qwWellChars");
			return (Criteria) this;
		}

		public Criteria andQwWellCharsIn(List<String> values) {
			addCriterion("QW_WELL_CHARS in", values, "qwWellChars");
			return (Criteria) this;
		}

		public Criteria andQwWellCharsNotIn(List<String> values) {
			addCriterion("QW_WELL_CHARS not in", values, "qwWellChars");
			return (Criteria) this;
		}

		public Criteria andQwWellCharsBetween(String value1, String value2) {
			addCriterion("QW_WELL_CHARS between", value1, value2, "qwWellChars");
			return (Criteria) this;
		}

		public Criteria andQwWellCharsNotBetween(String value1, String value2) {
			addCriterion("QW_WELL_CHARS not between", value1, value2,
					"qwWellChars");
			return (Criteria) this;
		}

		public Criteria andQwWellTypeIsNull() {
			addCriterion("QW_WELL_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andQwWellTypeIsNotNull() {
			addCriterion("QW_WELL_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andQwWellTypeEqualTo(String value) {
			addCriterion("QW_WELL_TYPE =", value, "qwWellType");
			return (Criteria) this;
		}

		public Criteria andQwWellTypeNotEqualTo(String value) {
			addCriterion("QW_WELL_TYPE <>", value, "qwWellType");
			return (Criteria) this;
		}

		public Criteria andQwWellTypeGreaterThan(String value) {
			addCriterion("QW_WELL_TYPE >", value, "qwWellType");
			return (Criteria) this;
		}

		public Criteria andQwWellTypeGreaterThanOrEqualTo(String value) {
			addCriterion("QW_WELL_TYPE >=", value, "qwWellType");
			return (Criteria) this;
		}

		public Criteria andQwWellTypeLessThan(String value) {
			addCriterion("QW_WELL_TYPE <", value, "qwWellType");
			return (Criteria) this;
		}

		public Criteria andQwWellTypeLessThanOrEqualTo(String value) {
			addCriterion("QW_WELL_TYPE <=", value, "qwWellType");
			return (Criteria) this;
		}

		public Criteria andQwWellTypeLike(String value) {
			addCriterion("QW_WELL_TYPE like", value, "qwWellType");
			return (Criteria) this;
		}

		public Criteria andQwWellTypeNotLike(String value) {
			addCriterion("QW_WELL_TYPE not like", value, "qwWellType");
			return (Criteria) this;
		}

		public Criteria andQwWellTypeIn(List<String> values) {
			addCriterion("QW_WELL_TYPE in", values, "qwWellType");
			return (Criteria) this;
		}

		public Criteria andQwWellTypeNotIn(List<String> values) {
			addCriterion("QW_WELL_TYPE not in", values, "qwWellType");
			return (Criteria) this;
		}

		public Criteria andQwWellTypeBetween(String value1, String value2) {
			addCriterion("QW_WELL_TYPE between", value1, value2, "qwWellType");
			return (Criteria) this;
		}

		public Criteria andQwWellTypeNotBetween(String value1, String value2) {
			addCriterion("QW_WELL_TYPE not between", value1, value2,
					"qwWellType");
			return (Criteria) this;
		}

		public Criteria andWlSnFlagIsNull() {
			addCriterion("WL_SN_FLAG is null");
			return (Criteria) this;
		}

		public Criteria andWlSnFlagIsNotNull() {
			addCriterion("WL_SN_FLAG is not null");
			return (Criteria) this;
		}

		public Criteria andWlSnFlagEqualTo(String value) {
			addCriterion("WL_SN_FLAG =", value, "wlSnFlag");
			return (Criteria) this;
		}

		public Criteria andWlSnFlagNotEqualTo(String value) {
			addCriterion("WL_SN_FLAG <>", value, "wlSnFlag");
			return (Criteria) this;
		}

		public Criteria andWlSnFlagGreaterThan(String value) {
			addCriterion("WL_SN_FLAG >", value, "wlSnFlag");
			return (Criteria) this;
		}

		public Criteria andWlSnFlagGreaterThanOrEqualTo(String value) {
			addCriterion("WL_SN_FLAG >=", value, "wlSnFlag");
			return (Criteria) this;
		}

		public Criteria andWlSnFlagLessThan(String value) {
			addCriterion("WL_SN_FLAG <", value, "wlSnFlag");
			return (Criteria) this;
		}

		public Criteria andWlSnFlagLessThanOrEqualTo(String value) {
			addCriterion("WL_SN_FLAG <=", value, "wlSnFlag");
			return (Criteria) this;
		}

		public Criteria andWlSnFlagLike(String value) {
			addCriterion("WL_SN_FLAG like", value, "wlSnFlag");
			return (Criteria) this;
		}

		public Criteria andWlSnFlagNotLike(String value) {
			addCriterion("WL_SN_FLAG not like", value, "wlSnFlag");
			return (Criteria) this;
		}

		public Criteria andWlSnFlagIn(List<String> values) {
			addCriterion("WL_SN_FLAG in", values, "wlSnFlag");
			return (Criteria) this;
		}

		public Criteria andWlSnFlagNotIn(List<String> values) {
			addCriterion("WL_SN_FLAG not in", values, "wlSnFlag");
			return (Criteria) this;
		}

		public Criteria andWlSnFlagBetween(String value1, String value2) {
			addCriterion("WL_SN_FLAG between", value1, value2, "wlSnFlag");
			return (Criteria) this;
		}

		public Criteria andWlSnFlagNotBetween(String value1, String value2) {
			addCriterion("WL_SN_FLAG not between", value1, value2, "wlSnFlag");
			return (Criteria) this;
		}

		public Criteria andWlBaselineFlagIsNull() {
			addCriterion("WL_BASELINE_FLAG is null");
			return (Criteria) this;
		}

		public Criteria andWlBaselineFlagIsNotNull() {
			addCriterion("WL_BASELINE_FLAG is not null");
			return (Criteria) this;
		}

		public Criteria andWlBaselineFlagEqualTo(String value) {
			addCriterion("WL_BASELINE_FLAG =", value, "wlBaselineFlag");
			return (Criteria) this;
		}

		public Criteria andWlBaselineFlagNotEqualTo(String value) {
			addCriterion("WL_BASELINE_FLAG <>", value, "wlBaselineFlag");
			return (Criteria) this;
		}

		public Criteria andWlBaselineFlagGreaterThan(String value) {
			addCriterion("WL_BASELINE_FLAG >", value, "wlBaselineFlag");
			return (Criteria) this;
		}

		public Criteria andWlBaselineFlagGreaterThanOrEqualTo(String value) {
			addCriterion("WL_BASELINE_FLAG >=", value, "wlBaselineFlag");
			return (Criteria) this;
		}

		public Criteria andWlBaselineFlagLessThan(String value) {
			addCriterion("WL_BASELINE_FLAG <", value, "wlBaselineFlag");
			return (Criteria) this;
		}

		public Criteria andWlBaselineFlagLessThanOrEqualTo(String value) {
			addCriterion("WL_BASELINE_FLAG <=", value, "wlBaselineFlag");
			return (Criteria) this;
		}

		public Criteria andWlBaselineFlagLike(String value) {
			addCriterion("WL_BASELINE_FLAG like", value, "wlBaselineFlag");
			return (Criteria) this;
		}

		public Criteria andWlBaselineFlagNotLike(String value) {
			addCriterion("WL_BASELINE_FLAG not like", value, "wlBaselineFlag");
			return (Criteria) this;
		}

		public Criteria andWlBaselineFlagIn(List<String> values) {
			addCriterion("WL_BASELINE_FLAG in", values, "wlBaselineFlag");
			return (Criteria) this;
		}

		public Criteria andWlBaselineFlagNotIn(List<String> values) {
			addCriterion("WL_BASELINE_FLAG not in", values, "wlBaselineFlag");
			return (Criteria) this;
		}

		public Criteria andWlBaselineFlagBetween(String value1, String value2) {
			addCriterion("WL_BASELINE_FLAG between", value1, value2,
					"wlBaselineFlag");
			return (Criteria) this;
		}

		public Criteria andWlBaselineFlagNotBetween(String value1, String value2) {
			addCriterion("WL_BASELINE_FLAG not between", value1, value2,
					"wlBaselineFlag");
			return (Criteria) this;
		}

		public Criteria andWlWellCharsIsNull() {
			addCriterion("WL_WELL_CHARS is null");
			return (Criteria) this;
		}

		public Criteria andWlWellCharsIsNotNull() {
			addCriterion("WL_WELL_CHARS is not null");
			return (Criteria) this;
		}

		public Criteria andWlWellCharsEqualTo(String value) {
			addCriterion("WL_WELL_CHARS =", value, "wlWellChars");
			return (Criteria) this;
		}

		public Criteria andWlWellCharsNotEqualTo(String value) {
			addCriterion("WL_WELL_CHARS <>", value, "wlWellChars");
			return (Criteria) this;
		}

		public Criteria andWlWellCharsGreaterThan(String value) {
			addCriterion("WL_WELL_CHARS >", value, "wlWellChars");
			return (Criteria) this;
		}

		public Criteria andWlWellCharsGreaterThanOrEqualTo(String value) {
			addCriterion("WL_WELL_CHARS >=", value, "wlWellChars");
			return (Criteria) this;
		}

		public Criteria andWlWellCharsLessThan(String value) {
			addCriterion("WL_WELL_CHARS <", value, "wlWellChars");
			return (Criteria) this;
		}

		public Criteria andWlWellCharsLessThanOrEqualTo(String value) {
			addCriterion("WL_WELL_CHARS <=", value, "wlWellChars");
			return (Criteria) this;
		}

		public Criteria andWlWellCharsLike(String value) {
			addCriterion("WL_WELL_CHARS like", value, "wlWellChars");
			return (Criteria) this;
		}

		public Criteria andWlWellCharsNotLike(String value) {
			addCriterion("WL_WELL_CHARS not like", value, "wlWellChars");
			return (Criteria) this;
		}

		public Criteria andWlWellCharsIn(List<String> values) {
			addCriterion("WL_WELL_CHARS in", values, "wlWellChars");
			return (Criteria) this;
		}

		public Criteria andWlWellCharsNotIn(List<String> values) {
			addCriterion("WL_WELL_CHARS not in", values, "wlWellChars");
			return (Criteria) this;
		}

		public Criteria andWlWellCharsBetween(String value1, String value2) {
			addCriterion("WL_WELL_CHARS between", value1, value2, "wlWellChars");
			return (Criteria) this;
		}

		public Criteria andWlWellCharsNotBetween(String value1, String value2) {
			addCriterion("WL_WELL_CHARS not between", value1, value2,
					"wlWellChars");
			return (Criteria) this;
		}

		public Criteria andWlWellTypeIsNull() {
			addCriterion("WL_WELL_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andWlWellTypeIsNotNull() {
			addCriterion("WL_WELL_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andWlWellTypeEqualTo(String value) {
			addCriterion("WL_WELL_TYPE =", value, "wlWellType");
			return (Criteria) this;
		}

		public Criteria andWlWellTypeNotEqualTo(String value) {
			addCriterion("WL_WELL_TYPE <>", value, "wlWellType");
			return (Criteria) this;
		}

		public Criteria andWlWellTypeGreaterThan(String value) {
			addCriterion("WL_WELL_TYPE >", value, "wlWellType");
			return (Criteria) this;
		}

		public Criteria andWlWellTypeGreaterThanOrEqualTo(String value) {
			addCriterion("WL_WELL_TYPE >=", value, "wlWellType");
			return (Criteria) this;
		}

		public Criteria andWlWellTypeLessThan(String value) {
			addCriterion("WL_WELL_TYPE <", value, "wlWellType");
			return (Criteria) this;
		}

		public Criteria andWlWellTypeLessThanOrEqualTo(String value) {
			addCriterion("WL_WELL_TYPE <=", value, "wlWellType");
			return (Criteria) this;
		}

		public Criteria andWlWellTypeLike(String value) {
			addCriterion("WL_WELL_TYPE like", value, "wlWellType");
			return (Criteria) this;
		}

		public Criteria andWlWellTypeNotLike(String value) {
			addCriterion("WL_WELL_TYPE not like", value, "wlWellType");
			return (Criteria) this;
		}

		public Criteria andWlWellTypeIn(List<String> values) {
			addCriterion("WL_WELL_TYPE in", values, "wlWellType");
			return (Criteria) this;
		}

		public Criteria andWlWellTypeNotIn(List<String> values) {
			addCriterion("WL_WELL_TYPE not in", values, "wlWellType");
			return (Criteria) this;
		}

		public Criteria andWlWellTypeBetween(String value1, String value2) {
			addCriterion("WL_WELL_TYPE between", value1, value2, "wlWellType");
			return (Criteria) this;
		}

		public Criteria andWlWellTypeNotBetween(String value1, String value2) {
			addCriterion("WL_WELL_TYPE not between", value1, value2,
					"wlWellType");
			return (Criteria) this;
		}

		public Criteria andDataProviderIsNull() {
			addCriterion("DATA_PROVIDER is null");
			return (Criteria) this;
		}

		public Criteria andDataProviderIsNotNull() {
			addCriterion("DATA_PROVIDER is not null");
			return (Criteria) this;
		}

		public Criteria andDataProviderEqualTo(String value) {
			addCriterion("DATA_PROVIDER =", value, "dataProvider");
			return (Criteria) this;
		}

		public Criteria andDataProviderNotEqualTo(String value) {
			addCriterion("DATA_PROVIDER <>", value, "dataProvider");
			return (Criteria) this;
		}

		public Criteria andDataProviderGreaterThan(String value) {
			addCriterion("DATA_PROVIDER >", value, "dataProvider");
			return (Criteria) this;
		}

		public Criteria andDataProviderGreaterThanOrEqualTo(String value) {
			addCriterion("DATA_PROVIDER >=", value, "dataProvider");
			return (Criteria) this;
		}

		public Criteria andDataProviderLessThan(String value) {
			addCriterion("DATA_PROVIDER <", value, "dataProvider");
			return (Criteria) this;
		}

		public Criteria andDataProviderLessThanOrEqualTo(String value) {
			addCriterion("DATA_PROVIDER <=", value, "dataProvider");
			return (Criteria) this;
		}

		public Criteria andDataProviderLike(String value) {
			addCriterion("DATA_PROVIDER like", value, "dataProvider");
			return (Criteria) this;
		}

		public Criteria andDataProviderNotLike(String value) {
			addCriterion("DATA_PROVIDER not like", value, "dataProvider");
			return (Criteria) this;
		}

		public Criteria andDataProviderIn(List<String> values) {
			addCriterion("DATA_PROVIDER in", values, "dataProvider");
			return (Criteria) this;
		}

		public Criteria andDataProviderNotIn(List<String> values) {
			addCriterion("DATA_PROVIDER not in", values, "dataProvider");
			return (Criteria) this;
		}

		public Criteria andDataProviderBetween(String value1, String value2) {
			addCriterion("DATA_PROVIDER between", value1, value2,
					"dataProvider");
			return (Criteria) this;
		}

		public Criteria andDataProviderNotBetween(String value1, String value2) {
			addCriterion("DATA_PROVIDER not between", value1, value2,
					"dataProvider");
			return (Criteria) this;
		}

		public Criteria andQwSysNameIsNull() {
			addCriterion("QW_SYS_NAME is null");
			return (Criteria) this;
		}

		public Criteria andQwSysNameIsNotNull() {
			addCriterion("QW_SYS_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andQwSysNameEqualTo(String value) {
			addCriterion("QW_SYS_NAME =", value, "qwSysName");
			return (Criteria) this;
		}

		public Criteria andQwSysNameNotEqualTo(String value) {
			addCriterion("QW_SYS_NAME <>", value, "qwSysName");
			return (Criteria) this;
		}

		public Criteria andQwSysNameGreaterThan(String value) {
			addCriterion("QW_SYS_NAME >", value, "qwSysName");
			return (Criteria) this;
		}

		public Criteria andQwSysNameGreaterThanOrEqualTo(String value) {
			addCriterion("QW_SYS_NAME >=", value, "qwSysName");
			return (Criteria) this;
		}

		public Criteria andQwSysNameLessThan(String value) {
			addCriterion("QW_SYS_NAME <", value, "qwSysName");
			return (Criteria) this;
		}

		public Criteria andQwSysNameLessThanOrEqualTo(String value) {
			addCriterion("QW_SYS_NAME <=", value, "qwSysName");
			return (Criteria) this;
		}

		public Criteria andQwSysNameLike(String value) {
			addCriterion("QW_SYS_NAME like", value, "qwSysName");
			return (Criteria) this;
		}

		public Criteria andQwSysNameNotLike(String value) {
			addCriterion("QW_SYS_NAME not like", value, "qwSysName");
			return (Criteria) this;
		}

		public Criteria andQwSysNameIn(List<String> values) {
			addCriterion("QW_SYS_NAME in", values, "qwSysName");
			return (Criteria) this;
		}

		public Criteria andQwSysNameNotIn(List<String> values) {
			addCriterion("QW_SYS_NAME not in", values, "qwSysName");
			return (Criteria) this;
		}

		public Criteria andQwSysNameBetween(String value1, String value2) {
			addCriterion("QW_SYS_NAME between", value1, value2, "qwSysName");
			return (Criteria) this;
		}

		public Criteria andQwSysNameNotBetween(String value1, String value2) {
			addCriterion("QW_SYS_NAME not between", value1, value2, "qwSysName");
			return (Criteria) this;
		}

		public Criteria andWlSysNameIsNull() {
			addCriterion("WL_SYS_NAME is null");
			return (Criteria) this;
		}

		public Criteria andWlSysNameIsNotNull() {
			addCriterion("WL_SYS_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andWlSysNameEqualTo(String value) {
			addCriterion("WL_SYS_NAME =", value, "wlSysName");
			return (Criteria) this;
		}

		public Criteria andWlSysNameNotEqualTo(String value) {
			addCriterion("WL_SYS_NAME <>", value, "wlSysName");
			return (Criteria) this;
		}

		public Criteria andWlSysNameGreaterThan(String value) {
			addCriterion("WL_SYS_NAME >", value, "wlSysName");
			return (Criteria) this;
		}

		public Criteria andWlSysNameGreaterThanOrEqualTo(String value) {
			addCriterion("WL_SYS_NAME >=", value, "wlSysName");
			return (Criteria) this;
		}

		public Criteria andWlSysNameLessThan(String value) {
			addCriterion("WL_SYS_NAME <", value, "wlSysName");
			return (Criteria) this;
		}

		public Criteria andWlSysNameLessThanOrEqualTo(String value) {
			addCriterion("WL_SYS_NAME <=", value, "wlSysName");
			return (Criteria) this;
		}

		public Criteria andWlSysNameLike(String value) {
			addCriterion("WL_SYS_NAME like", value, "wlSysName");
			return (Criteria) this;
		}

		public Criteria andWlSysNameNotLike(String value) {
			addCriterion("WL_SYS_NAME not like", value, "wlSysName");
			return (Criteria) this;
		}

		public Criteria andWlSysNameIn(List<String> values) {
			addCriterion("WL_SYS_NAME in", values, "wlSysName");
			return (Criteria) this;
		}

		public Criteria andWlSysNameNotIn(List<String> values) {
			addCriterion("WL_SYS_NAME not in", values, "wlSysName");
			return (Criteria) this;
		}

		public Criteria andWlSysNameBetween(String value1, String value2) {
			addCriterion("WL_SYS_NAME between", value1, value2, "wlSysName");
			return (Criteria) this;
		}

		public Criteria andWlSysNameNotBetween(String value1, String value2) {
			addCriterion("WL_SYS_NAME not between", value1, value2, "wlSysName");
			return (Criteria) this;
		}

		public Criteria andInsertDateIsNull() {
			addCriterion("INSERT_DATE is null");
			return (Criteria) this;
		}

		public Criteria andInsertDateIsNotNull() {
			addCriterion("INSERT_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andInsertDateEqualTo(Date value) {
			addCriterion("INSERT_DATE =", value, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateNotEqualTo(Date value) {
			addCriterion("INSERT_DATE <>", value, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateGreaterThan(Date value) {
			addCriterion("INSERT_DATE >", value, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateGreaterThanOrEqualTo(Date value) {
			addCriterion("INSERT_DATE >=", value, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateLessThan(Date value) {
			addCriterion("INSERT_DATE <", value, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateLessThanOrEqualTo(Date value) {
			addCriterion("INSERT_DATE <=", value, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateIn(List<Date> values) {
			addCriterion("INSERT_DATE in", values, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateNotIn(List<Date> values) {
			addCriterion("INSERT_DATE not in", values, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateBetween(Date value1, Date value2) {
			addCriterion("INSERT_DATE between", value1, value2, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateNotBetween(Date value1, Date value2) {
			addCriterion("INSERT_DATE not between", value1, value2,
					"insertDate");
			return (Criteria) this;
		}

		public Criteria andMySiteidIsNull() {
			addCriterion("MY_SITEID is null");
			return (Criteria) this;
		}

		public Criteria andMySiteidIsNotNull() {
			addCriterion("MY_SITEID is not null");
			return (Criteria) this;
		}

		public Criteria andMySiteidEqualTo(String value) {
			addCriterion("MY_SITEID =", value, "mySiteid");
			return (Criteria) this;
		}

		public Criteria andMySiteidNotEqualTo(String value) {
			addCriterion("MY_SITEID <>", value, "mySiteid");
			return (Criteria) this;
		}

		public Criteria andMySiteidGreaterThan(String value) {
			addCriterion("MY_SITEID >", value, "mySiteid");
			return (Criteria) this;
		}

		public Criteria andMySiteidGreaterThanOrEqualTo(String value) {
			addCriterion("MY_SITEID >=", value, "mySiteid");
			return (Criteria) this;
		}

		public Criteria andMySiteidLessThan(String value) {
			addCriterion("MY_SITEID <", value, "mySiteid");
			return (Criteria) this;
		}

		public Criteria andMySiteidLessThanOrEqualTo(String value) {
			addCriterion("MY_SITEID <=", value, "mySiteid");
			return (Criteria) this;
		}

		public Criteria andMySiteidLike(String value) {
			addCriterion("MY_SITEID like", value, "mySiteid");
			return (Criteria) this;
		}

		public Criteria andMySiteidNotLike(String value) {
			addCriterion("MY_SITEID not like", value, "mySiteid");
			return (Criteria) this;
		}

		public Criteria andMySiteidIn(List<String> values) {
			addCriterion("MY_SITEID in", values, "mySiteid");
			return (Criteria) this;
		}

		public Criteria andMySiteidNotIn(List<String> values) {
			addCriterion("MY_SITEID not in", values, "mySiteid");
			return (Criteria) this;
		}

		public Criteria andMySiteidBetween(String value1, String value2) {
			addCriterion("MY_SITEID between", value1, value2, "mySiteid");
			return (Criteria) this;
		}

		public Criteria andMySiteidNotBetween(String value1, String value2) {
			addCriterion("MY_SITEID not between", value1, value2, "mySiteid");
			return (Criteria) this;
		}

		public Criteria andDisplayFlagIsNull() {
			addCriterion("DISPLAY_FLAG is null");
			return (Criteria) this;
		}

		public Criteria andDisplayFlagIsNotNull() {
			addCriterion("DISPLAY_FLAG is not null");
			return (Criteria) this;
		}

		public Criteria andDisplayFlagEqualTo(String value) {
			addCriterion("DISPLAY_FLAG =", value, "displayFlag");
			return (Criteria) this;
		}

		public Criteria andDisplayFlagNotEqualTo(String value) {
			addCriterion("DISPLAY_FLAG <>", value, "displayFlag");
			return (Criteria) this;
		}

		public Criteria andDisplayFlagGreaterThan(String value) {
			addCriterion("DISPLAY_FLAG >", value, "displayFlag");
			return (Criteria) this;
		}

		public Criteria andDisplayFlagGreaterThanOrEqualTo(String value) {
			addCriterion("DISPLAY_FLAG >=", value, "displayFlag");
			return (Criteria) this;
		}

		public Criteria andDisplayFlagLessThan(String value) {
			addCriterion("DISPLAY_FLAG <", value, "displayFlag");
			return (Criteria) this;
		}

		public Criteria andDisplayFlagLessThanOrEqualTo(String value) {
			addCriterion("DISPLAY_FLAG <=", value, "displayFlag");
			return (Criteria) this;
		}

		public Criteria andDisplayFlagLike(String value) {
			addCriterion("DISPLAY_FLAG like", value, "displayFlag");
			return (Criteria) this;
		}

		public Criteria andDisplayFlagNotLike(String value) {
			addCriterion("DISPLAY_FLAG not like", value, "displayFlag");
			return (Criteria) this;
		}

		public Criteria andDisplayFlagIn(List<String> values) {
			addCriterion("DISPLAY_FLAG in", values, "displayFlag");
			return (Criteria) this;
		}

		public Criteria andDisplayFlagNotIn(List<String> values) {
			addCriterion("DISPLAY_FLAG not in", values, "displayFlag");
			return (Criteria) this;
		}

		public Criteria andDisplayFlagBetween(String value1, String value2) {
			addCriterion("DISPLAY_FLAG between", value1, value2, "displayFlag");
			return (Criteria) this;
		}

		public Criteria andDisplayFlagNotBetween(String value1, String value2) {
			addCriterion("DISPLAY_FLAG not between", value1, value2,
					"displayFlag");
			return (Criteria) this;
		}

		public Criteria andWlDataProviderIsNull() {
			addCriterion("WL_DATA_PROVIDER is null");
			return (Criteria) this;
		}

		public Criteria andWlDataProviderIsNotNull() {
			addCriterion("WL_DATA_PROVIDER is not null");
			return (Criteria) this;
		}

		public Criteria andWlDataProviderEqualTo(String value) {
			addCriterion("WL_DATA_PROVIDER =", value, "wlDataProvider");
			return (Criteria) this;
		}

		public Criteria andWlDataProviderNotEqualTo(String value) {
			addCriterion("WL_DATA_PROVIDER <>", value, "wlDataProvider");
			return (Criteria) this;
		}

		public Criteria andWlDataProviderGreaterThan(String value) {
			addCriterion("WL_DATA_PROVIDER >", value, "wlDataProvider");
			return (Criteria) this;
		}

		public Criteria andWlDataProviderGreaterThanOrEqualTo(String value) {
			addCriterion("WL_DATA_PROVIDER >=", value, "wlDataProvider");
			return (Criteria) this;
		}

		public Criteria andWlDataProviderLessThan(String value) {
			addCriterion("WL_DATA_PROVIDER <", value, "wlDataProvider");
			return (Criteria) this;
		}

		public Criteria andWlDataProviderLessThanOrEqualTo(String value) {
			addCriterion("WL_DATA_PROVIDER <=", value, "wlDataProvider");
			return (Criteria) this;
		}

		public Criteria andWlDataProviderLike(String value) {
			addCriterion("WL_DATA_PROVIDER like", value, "wlDataProvider");
			return (Criteria) this;
		}

		public Criteria andWlDataProviderNotLike(String value) {
			addCriterion("WL_DATA_PROVIDER not like", value, "wlDataProvider");
			return (Criteria) this;
		}

		public Criteria andWlDataProviderIn(List<String> values) {
			addCriterion("WL_DATA_PROVIDER in", values, "wlDataProvider");
			return (Criteria) this;
		}

		public Criteria andWlDataProviderNotIn(List<String> values) {
			addCriterion("WL_DATA_PROVIDER not in", values, "wlDataProvider");
			return (Criteria) this;
		}

		public Criteria andWlDataProviderBetween(String value1, String value2) {
			addCriterion("WL_DATA_PROVIDER between", value1, value2,
					"wlDataProvider");
			return (Criteria) this;
		}

		public Criteria andWlDataProviderNotBetween(String value1, String value2) {
			addCriterion("WL_DATA_PROVIDER not between", value1, value2,
					"wlDataProvider");
			return (Criteria) this;
		}

		public Criteria andQwDataProviderIsNull() {
			addCriterion("QW_DATA_PROVIDER is null");
			return (Criteria) this;
		}

		public Criteria andQwDataProviderIsNotNull() {
			addCriterion("QW_DATA_PROVIDER is not null");
			return (Criteria) this;
		}

		public Criteria andQwDataProviderEqualTo(String value) {
			addCriterion("QW_DATA_PROVIDER =", value, "qwDataProvider");
			return (Criteria) this;
		}

		public Criteria andQwDataProviderNotEqualTo(String value) {
			addCriterion("QW_DATA_PROVIDER <>", value, "qwDataProvider");
			return (Criteria) this;
		}

		public Criteria andQwDataProviderGreaterThan(String value) {
			addCriterion("QW_DATA_PROVIDER >", value, "qwDataProvider");
			return (Criteria) this;
		}

		public Criteria andQwDataProviderGreaterThanOrEqualTo(String value) {
			addCriterion("QW_DATA_PROVIDER >=", value, "qwDataProvider");
			return (Criteria) this;
		}

		public Criteria andQwDataProviderLessThan(String value) {
			addCriterion("QW_DATA_PROVIDER <", value, "qwDataProvider");
			return (Criteria) this;
		}

		public Criteria andQwDataProviderLessThanOrEqualTo(String value) {
			addCriterion("QW_DATA_PROVIDER <=", value, "qwDataProvider");
			return (Criteria) this;
		}

		public Criteria andQwDataProviderLike(String value) {
			addCriterion("QW_DATA_PROVIDER like", value, "qwDataProvider");
			return (Criteria) this;
		}

		public Criteria andQwDataProviderNotLike(String value) {
			addCriterion("QW_DATA_PROVIDER not like", value, "qwDataProvider");
			return (Criteria) this;
		}

		public Criteria andQwDataProviderIn(List<String> values) {
			addCriterion("QW_DATA_PROVIDER in", values, "qwDataProvider");
			return (Criteria) this;
		}

		public Criteria andQwDataProviderNotIn(List<String> values) {
			addCriterion("QW_DATA_PROVIDER not in", values, "qwDataProvider");
			return (Criteria) this;
		}

		public Criteria andQwDataProviderBetween(String value1, String value2) {
			addCriterion("QW_DATA_PROVIDER between", value1, value2,
					"qwDataProvider");
			return (Criteria) this;
		}

		public Criteria andQwDataProviderNotBetween(String value1, String value2) {
			addCriterion("QW_DATA_PROVIDER not between", value1, value2,
					"qwDataProvider");
			return (Criteria) this;
		}

		public Criteria andLithDataProviderIsNull() {
			addCriterion("LITH_DATA_PROVIDER is null");
			return (Criteria) this;
		}

		public Criteria andLithDataProviderIsNotNull() {
			addCriterion("LITH_DATA_PROVIDER is not null");
			return (Criteria) this;
		}

		public Criteria andLithDataProviderEqualTo(String value) {
			addCriterion("LITH_DATA_PROVIDER =", value, "lithDataProvider");
			return (Criteria) this;
		}

		public Criteria andLithDataProviderNotEqualTo(String value) {
			addCriterion("LITH_DATA_PROVIDER <>", value, "lithDataProvider");
			return (Criteria) this;
		}

		public Criteria andLithDataProviderGreaterThan(String value) {
			addCriterion("LITH_DATA_PROVIDER >", value, "lithDataProvider");
			return (Criteria) this;
		}

		public Criteria andLithDataProviderGreaterThanOrEqualTo(String value) {
			addCriterion("LITH_DATA_PROVIDER >=", value, "lithDataProvider");
			return (Criteria) this;
		}

		public Criteria andLithDataProviderLessThan(String value) {
			addCriterion("LITH_DATA_PROVIDER <", value, "lithDataProvider");
			return (Criteria) this;
		}

		public Criteria andLithDataProviderLessThanOrEqualTo(String value) {
			addCriterion("LITH_DATA_PROVIDER <=", value, "lithDataProvider");
			return (Criteria) this;
		}

		public Criteria andLithDataProviderLike(String value) {
			addCriterion("LITH_DATA_PROVIDER like", value, "lithDataProvider");
			return (Criteria) this;
		}

		public Criteria andLithDataProviderNotLike(String value) {
			addCriterion("LITH_DATA_PROVIDER not like", value,
					"lithDataProvider");
			return (Criteria) this;
		}

		public Criteria andLithDataProviderIn(List<String> values) {
			addCriterion("LITH_DATA_PROVIDER in", values, "lithDataProvider");
			return (Criteria) this;
		}

		public Criteria andLithDataProviderNotIn(List<String> values) {
			addCriterion("LITH_DATA_PROVIDER not in", values,
					"lithDataProvider");
			return (Criteria) this;
		}

		public Criteria andLithDataProviderBetween(String value1, String value2) {
			addCriterion("LITH_DATA_PROVIDER between", value1, value2,
					"lithDataProvider");
			return (Criteria) this;
		}

		public Criteria andLithDataProviderNotBetween(String value1,
				String value2) {
			addCriterion("LITH_DATA_PROVIDER not between", value1, value2,
					"lithDataProvider");
			return (Criteria) this;
		}

		public Criteria andConstDataProviderIsNull() {
			addCriterion("CONST_DATA_PROVIDER is null");
			return (Criteria) this;
		}

		public Criteria andConstDataProviderIsNotNull() {
			addCriterion("CONST_DATA_PROVIDER is not null");
			return (Criteria) this;
		}

		public Criteria andConstDataProviderEqualTo(String value) {
			addCriterion("CONST_DATA_PROVIDER =", value, "constDataProvider");
			return (Criteria) this;
		}

		public Criteria andConstDataProviderNotEqualTo(String value) {
			addCriterion("CONST_DATA_PROVIDER <>", value, "constDataProvider");
			return (Criteria) this;
		}

		public Criteria andConstDataProviderGreaterThan(String value) {
			addCriterion("CONST_DATA_PROVIDER >", value, "constDataProvider");
			return (Criteria) this;
		}

		public Criteria andConstDataProviderGreaterThanOrEqualTo(String value) {
			addCriterion("CONST_DATA_PROVIDER >=", value, "constDataProvider");
			return (Criteria) this;
		}

		public Criteria andConstDataProviderLessThan(String value) {
			addCriterion("CONST_DATA_PROVIDER <", value, "constDataProvider");
			return (Criteria) this;
		}

		public Criteria andConstDataProviderLessThanOrEqualTo(String value) {
			addCriterion("CONST_DATA_PROVIDER <=", value, "constDataProvider");
			return (Criteria) this;
		}

		public Criteria andConstDataProviderLike(String value) {
			addCriterion("CONST_DATA_PROVIDER like", value, "constDataProvider");
			return (Criteria) this;
		}

		public Criteria andConstDataProviderNotLike(String value) {
			addCriterion("CONST_DATA_PROVIDER not like", value,
					"constDataProvider");
			return (Criteria) this;
		}

		public Criteria andConstDataProviderIn(List<String> values) {
			addCriterion("CONST_DATA_PROVIDER in", values, "constDataProvider");
			return (Criteria) this;
		}

		public Criteria andConstDataProviderNotIn(List<String> values) {
			addCriterion("CONST_DATA_PROVIDER not in", values,
					"constDataProvider");
			return (Criteria) this;
		}

		public Criteria andConstDataProviderBetween(String value1, String value2) {
			addCriterion("CONST_DATA_PROVIDER between", value1, value2,
					"constDataProvider");
			return (Criteria) this;
		}

		public Criteria andConstDataProviderNotBetween(String value1,
				String value2) {
			addCriterion("CONST_DATA_PROVIDER not between", value1, value2,
					"constDataProvider");
			return (Criteria) this;
		}

		public Criteria andWellDepthIsNull() {
			addCriterion("WELL_DEPTH is null");
			return (Criteria) this;
		}

		public Criteria andWellDepthIsNotNull() {
			addCriterion("WELL_DEPTH is not null");
			return (Criteria) this;
		}

		public Criteria andWellDepthEqualTo(Double value) {
			addCriterion("WELL_DEPTH =", value, "wellDepth");
			return (Criteria) this;
		}

		public Criteria andWellDepthNotEqualTo(Double value) {
			addCriterion("WELL_DEPTH <>", value, "wellDepth");
			return (Criteria) this;
		}

		public Criteria andWellDepthGreaterThan(Double value) {
			addCriterion("WELL_DEPTH >", value, "wellDepth");
			return (Criteria) this;
		}

		public Criteria andWellDepthGreaterThanOrEqualTo(Double value) {
			addCriterion("WELL_DEPTH >=", value, "wellDepth");
			return (Criteria) this;
		}

		public Criteria andWellDepthLessThan(Double value) {
			addCriterion("WELL_DEPTH <", value, "wellDepth");
			return (Criteria) this;
		}

		public Criteria andWellDepthLessThanOrEqualTo(Double value) {
			addCriterion("WELL_DEPTH <=", value, "wellDepth");
			return (Criteria) this;
		}

		public Criteria andWellDepthIn(List<Double> values) {
			addCriterion("WELL_DEPTH in", values, "wellDepth");
			return (Criteria) this;
		}

		public Criteria andWellDepthNotIn(List<Double> values) {
			addCriterion("WELL_DEPTH not in", values, "wellDepth");
			return (Criteria) this;
		}

		public Criteria andWellDepthBetween(Double value1, Double value2) {
			addCriterion("WELL_DEPTH between", value1, value2, "wellDepth");
			return (Criteria) this;
		}

		public Criteria andWellDepthNotBetween(Double value1, Double value2) {
			addCriterion("WELL_DEPTH not between", value1, value2, "wellDepth");
			return (Criteria) this;
		}

		public Criteria andWellDepthUnitsIsNull() {
			addCriterion("WELL_DEPTH_UNITS is null");
			return (Criteria) this;
		}

		public Criteria andWellDepthUnitsIsNotNull() {
			addCriterion("WELL_DEPTH_UNITS is not null");
			return (Criteria) this;
		}

		public Criteria andWellDepthUnitsEqualTo(String value) {
			addCriterion("WELL_DEPTH_UNITS =", value, "wellDepthUnits");
			return (Criteria) this;
		}

		public Criteria andWellDepthUnitsNotEqualTo(String value) {
			addCriterion("WELL_DEPTH_UNITS <>", value, "wellDepthUnits");
			return (Criteria) this;
		}

		public Criteria andWellDepthUnitsGreaterThan(String value) {
			addCriterion("WELL_DEPTH_UNITS >", value, "wellDepthUnits");
			return (Criteria) this;
		}

		public Criteria andWellDepthUnitsGreaterThanOrEqualTo(String value) {
			addCriterion("WELL_DEPTH_UNITS >=", value, "wellDepthUnits");
			return (Criteria) this;
		}

		public Criteria andWellDepthUnitsLessThan(String value) {
			addCriterion("WELL_DEPTH_UNITS <", value, "wellDepthUnits");
			return (Criteria) this;
		}

		public Criteria andWellDepthUnitsLessThanOrEqualTo(String value) {
			addCriterion("WELL_DEPTH_UNITS <=", value, "wellDepthUnits");
			return (Criteria) this;
		}

		public Criteria andWellDepthUnitsLike(String value) {
			addCriterion("WELL_DEPTH_UNITS like", value, "wellDepthUnits");
			return (Criteria) this;
		}

		public Criteria andWellDepthUnitsNotLike(String value) {
			addCriterion("WELL_DEPTH_UNITS not like", value, "wellDepthUnits");
			return (Criteria) this;
		}

		public Criteria andWellDepthUnitsIn(List<String> values) {
			addCriterion("WELL_DEPTH_UNITS in", values, "wellDepthUnits");
			return (Criteria) this;
		}

		public Criteria andWellDepthUnitsNotIn(List<String> values) {
			addCriterion("WELL_DEPTH_UNITS not in", values, "wellDepthUnits");
			return (Criteria) this;
		}

		public Criteria andWellDepthUnitsBetween(String value1, String value2) {
			addCriterion("WELL_DEPTH_UNITS between", value1, value2,
					"wellDepthUnits");
			return (Criteria) this;
		}

		public Criteria andWellDepthUnitsNotBetween(String value1, String value2) {
			addCriterion("WELL_DEPTH_UNITS not between", value1, value2,
					"wellDepthUnits");
			return (Criteria) this;
		}

		public Criteria andLinkIsNull() {
			addCriterion("LINK is null");
			return (Criteria) this;
		}

		public Criteria andLinkIsNotNull() {
			addCriterion("LINK is not null");
			return (Criteria) this;
		}

		public Criteria andLinkEqualTo(String value) {
			addCriterion("LINK =", value, "link");
			return (Criteria) this;
		}

		public Criteria andLinkNotEqualTo(String value) {
			addCriterion("LINK <>", value, "link");
			return (Criteria) this;
		}

		public Criteria andLinkGreaterThan(String value) {
			addCriterion("LINK >", value, "link");
			return (Criteria) this;
		}

		public Criteria andLinkGreaterThanOrEqualTo(String value) {
			addCriterion("LINK >=", value, "link");
			return (Criteria) this;
		}

		public Criteria andLinkLessThan(String value) {
			addCriterion("LINK <", value, "link");
			return (Criteria) this;
		}

		public Criteria andLinkLessThanOrEqualTo(String value) {
			addCriterion("LINK <=", value, "link");
			return (Criteria) this;
		}

		public Criteria andLinkLike(String value) {
			addCriterion("LINK like", value, "link");
			return (Criteria) this;
		}

		public Criteria andLinkNotLike(String value) {
			addCriterion("LINK not like", value, "link");
			return (Criteria) this;
		}

		public Criteria andLinkIn(List<String> values) {
			addCriterion("LINK in", values, "link");
			return (Criteria) this;
		}

		public Criteria andLinkNotIn(List<String> values) {
			addCriterion("LINK not in", values, "link");
			return (Criteria) this;
		}

		public Criteria andLinkBetween(String value1, String value2) {
			addCriterion("LINK between", value1, value2, "link");
			return (Criteria) this;
		}

		public Criteria andLinkNotBetween(String value1, String value2) {
			addCriterion("LINK not between", value1, value2, "link");
			return (Criteria) this;
		}

		public Criteria andWlWellPurposeIsNull() {
			addCriterion("WL_WELL_PURPOSE is null");
			return (Criteria) this;
		}

		public Criteria andWlWellPurposeIsNotNull() {
			addCriterion("WL_WELL_PURPOSE is not null");
			return (Criteria) this;
		}

		public Criteria andWlWellPurposeEqualTo(String value) {
			addCriterion("WL_WELL_PURPOSE =", value, "wlWellPurpose");
			return (Criteria) this;
		}

		public Criteria andWlWellPurposeNotEqualTo(String value) {
			addCriterion("WL_WELL_PURPOSE <>", value, "wlWellPurpose");
			return (Criteria) this;
		}

		public Criteria andWlWellPurposeGreaterThan(String value) {
			addCriterion("WL_WELL_PURPOSE >", value, "wlWellPurpose");
			return (Criteria) this;
		}

		public Criteria andWlWellPurposeGreaterThanOrEqualTo(String value) {
			addCriterion("WL_WELL_PURPOSE >=", value, "wlWellPurpose");
			return (Criteria) this;
		}

		public Criteria andWlWellPurposeLessThan(String value) {
			addCriterion("WL_WELL_PURPOSE <", value, "wlWellPurpose");
			return (Criteria) this;
		}

		public Criteria andWlWellPurposeLessThanOrEqualTo(String value) {
			addCriterion("WL_WELL_PURPOSE <=", value, "wlWellPurpose");
			return (Criteria) this;
		}

		public Criteria andWlWellPurposeLike(String value) {
			addCriterion("WL_WELL_PURPOSE like", value, "wlWellPurpose");
			return (Criteria) this;
		}

		public Criteria andWlWellPurposeNotLike(String value) {
			addCriterion("WL_WELL_PURPOSE not like", value, "wlWellPurpose");
			return (Criteria) this;
		}

		public Criteria andWlWellPurposeIn(List<String> values) {
			addCriterion("WL_WELL_PURPOSE in", values, "wlWellPurpose");
			return (Criteria) this;
		}

		public Criteria andWlWellPurposeNotIn(List<String> values) {
			addCriterion("WL_WELL_PURPOSE not in", values, "wlWellPurpose");
			return (Criteria) this;
		}

		public Criteria andWlWellPurposeBetween(String value1, String value2) {
			addCriterion("WL_WELL_PURPOSE between", value1, value2,
					"wlWellPurpose");
			return (Criteria) this;
		}

		public Criteria andWlWellPurposeNotBetween(String value1, String value2) {
			addCriterion("WL_WELL_PURPOSE not between", value1, value2,
					"wlWellPurpose");
			return (Criteria) this;
		}

		public Criteria andQwWellPurposeIsNull() {
			addCriterion("QW_WELL_PURPOSE is null");
			return (Criteria) this;
		}

		public Criteria andQwWellPurposeIsNotNull() {
			addCriterion("QW_WELL_PURPOSE is not null");
			return (Criteria) this;
		}

		public Criteria andQwWellPurposeEqualTo(String value) {
			addCriterion("QW_WELL_PURPOSE =", value, "qwWellPurpose");
			return (Criteria) this;
		}

		public Criteria andQwWellPurposeNotEqualTo(String value) {
			addCriterion("QW_WELL_PURPOSE <>", value, "qwWellPurpose");
			return (Criteria) this;
		}

		public Criteria andQwWellPurposeGreaterThan(String value) {
			addCriterion("QW_WELL_PURPOSE >", value, "qwWellPurpose");
			return (Criteria) this;
		}

		public Criteria andQwWellPurposeGreaterThanOrEqualTo(String value) {
			addCriterion("QW_WELL_PURPOSE >=", value, "qwWellPurpose");
			return (Criteria) this;
		}

		public Criteria andQwWellPurposeLessThan(String value) {
			addCriterion("QW_WELL_PURPOSE <", value, "qwWellPurpose");
			return (Criteria) this;
		}

		public Criteria andQwWellPurposeLessThanOrEqualTo(String value) {
			addCriterion("QW_WELL_PURPOSE <=", value, "qwWellPurpose");
			return (Criteria) this;
		}

		public Criteria andQwWellPurposeLike(String value) {
			addCriterion("QW_WELL_PURPOSE like", value, "qwWellPurpose");
			return (Criteria) this;
		}

		public Criteria andQwWellPurposeNotLike(String value) {
			addCriterion("QW_WELL_PURPOSE not like", value, "qwWellPurpose");
			return (Criteria) this;
		}

		public Criteria andQwWellPurposeIn(List<String> values) {
			addCriterion("QW_WELL_PURPOSE in", values, "qwWellPurpose");
			return (Criteria) this;
		}

		public Criteria andQwWellPurposeNotIn(List<String> values) {
			addCriterion("QW_WELL_PURPOSE not in", values, "qwWellPurpose");
			return (Criteria) this;
		}

		public Criteria andQwWellPurposeBetween(String value1, String value2) {
			addCriterion("QW_WELL_PURPOSE between", value1, value2,
					"qwWellPurpose");
			return (Criteria) this;
		}

		public Criteria andQwWellPurposeNotBetween(String value1, String value2) {
			addCriterion("QW_WELL_PURPOSE not between", value1, value2,
					"qwWellPurpose");
			return (Criteria) this;
		}

		public Criteria andWlWellPurposeNotesIsNull() {
			addCriterion("WL_WELL_PURPOSE_NOTES is null");
			return (Criteria) this;
		}

		public Criteria andWlWellPurposeNotesIsNotNull() {
			addCriterion("WL_WELL_PURPOSE_NOTES is not null");
			return (Criteria) this;
		}

		public Criteria andWlWellPurposeNotesEqualTo(String value) {
			addCriterion("WL_WELL_PURPOSE_NOTES =", value, "wlWellPurposeNotes");
			return (Criteria) this;
		}

		public Criteria andWlWellPurposeNotesNotEqualTo(String value) {
			addCriterion("WL_WELL_PURPOSE_NOTES <>", value,
					"wlWellPurposeNotes");
			return (Criteria) this;
		}

		public Criteria andWlWellPurposeNotesGreaterThan(String value) {
			addCriterion("WL_WELL_PURPOSE_NOTES >", value, "wlWellPurposeNotes");
			return (Criteria) this;
		}

		public Criteria andWlWellPurposeNotesGreaterThanOrEqualTo(String value) {
			addCriterion("WL_WELL_PURPOSE_NOTES >=", value,
					"wlWellPurposeNotes");
			return (Criteria) this;
		}

		public Criteria andWlWellPurposeNotesLessThan(String value) {
			addCriterion("WL_WELL_PURPOSE_NOTES <", value, "wlWellPurposeNotes");
			return (Criteria) this;
		}

		public Criteria andWlWellPurposeNotesLessThanOrEqualTo(String value) {
			addCriterion("WL_WELL_PURPOSE_NOTES <=", value,
					"wlWellPurposeNotes");
			return (Criteria) this;
		}

		public Criteria andWlWellPurposeNotesLike(String value) {
			addCriterion("WL_WELL_PURPOSE_NOTES like", value,
					"wlWellPurposeNotes");
			return (Criteria) this;
		}

		public Criteria andWlWellPurposeNotesNotLike(String value) {
			addCriterion("WL_WELL_PURPOSE_NOTES not like", value,
					"wlWellPurposeNotes");
			return (Criteria) this;
		}

		public Criteria andWlWellPurposeNotesIn(List<String> values) {
			addCriterion("WL_WELL_PURPOSE_NOTES in", values,
					"wlWellPurposeNotes");
			return (Criteria) this;
		}

		public Criteria andWlWellPurposeNotesNotIn(List<String> values) {
			addCriterion("WL_WELL_PURPOSE_NOTES not in", values,
					"wlWellPurposeNotes");
			return (Criteria) this;
		}

		public Criteria andWlWellPurposeNotesBetween(String value1,
				String value2) {
			addCriterion("WL_WELL_PURPOSE_NOTES between", value1, value2,
					"wlWellPurposeNotes");
			return (Criteria) this;
		}

		public Criteria andWlWellPurposeNotesNotBetween(String value1,
				String value2) {
			addCriterion("WL_WELL_PURPOSE_NOTES not between", value1, value2,
					"wlWellPurposeNotes");
			return (Criteria) this;
		}

		public Criteria andQwWellPurposeNotesIsNull() {
			addCriterion("QW_WELL_PURPOSE_NOTES is null");
			return (Criteria) this;
		}

		public Criteria andQwWellPurposeNotesIsNotNull() {
			addCriterion("QW_WELL_PURPOSE_NOTES is not null");
			return (Criteria) this;
		}

		public Criteria andQwWellPurposeNotesEqualTo(String value) {
			addCriterion("QW_WELL_PURPOSE_NOTES =", value, "qwWellPurposeNotes");
			return (Criteria) this;
		}

		public Criteria andQwWellPurposeNotesNotEqualTo(String value) {
			addCriterion("QW_WELL_PURPOSE_NOTES <>", value,
					"qwWellPurposeNotes");
			return (Criteria) this;
		}

		public Criteria andQwWellPurposeNotesGreaterThan(String value) {
			addCriterion("QW_WELL_PURPOSE_NOTES >", value, "qwWellPurposeNotes");
			return (Criteria) this;
		}

		public Criteria andQwWellPurposeNotesGreaterThanOrEqualTo(String value) {
			addCriterion("QW_WELL_PURPOSE_NOTES >=", value,
					"qwWellPurposeNotes");
			return (Criteria) this;
		}

		public Criteria andQwWellPurposeNotesLessThan(String value) {
			addCriterion("QW_WELL_PURPOSE_NOTES <", value, "qwWellPurposeNotes");
			return (Criteria) this;
		}

		public Criteria andQwWellPurposeNotesLessThanOrEqualTo(String value) {
			addCriterion("QW_WELL_PURPOSE_NOTES <=", value,
					"qwWellPurposeNotes");
			return (Criteria) this;
		}

		public Criteria andQwWellPurposeNotesLike(String value) {
			addCriterion("QW_WELL_PURPOSE_NOTES like", value,
					"qwWellPurposeNotes");
			return (Criteria) this;
		}

		public Criteria andQwWellPurposeNotesNotLike(String value) {
			addCriterion("QW_WELL_PURPOSE_NOTES not like", value,
					"qwWellPurposeNotes");
			return (Criteria) this;
		}

		public Criteria andQwWellPurposeNotesIn(List<String> values) {
			addCriterion("QW_WELL_PURPOSE_NOTES in", values,
					"qwWellPurposeNotes");
			return (Criteria) this;
		}

		public Criteria andQwWellPurposeNotesNotIn(List<String> values) {
			addCriterion("QW_WELL_PURPOSE_NOTES not in", values,
					"qwWellPurposeNotes");
			return (Criteria) this;
		}

		public Criteria andQwWellPurposeNotesBetween(String value1,
				String value2) {
			addCriterion("QW_WELL_PURPOSE_NOTES between", value1, value2,
					"qwWellPurposeNotes");
			return (Criteria) this;
		}

		public Criteria andQwWellPurposeNotesNotBetween(String value1,
				String value2) {
			addCriterion("QW_WELL_PURPOSE_NOTES not between", value1, value2,
					"qwWellPurposeNotes");
			return (Criteria) this;
		}

		public Criteria andStateCdIsNull() {
			addCriterion("STATE_CD is null");
			return (Criteria) this;
		}

		public Criteria andStateCdIsNotNull() {
			addCriterion("STATE_CD is not null");
			return (Criteria) this;
		}

		public Criteria andStateCdEqualTo(Integer value) {
			addCriterion("STATE_CD =", value, "stateCd");
			return (Criteria) this;
		}

		public Criteria andStateCdNotEqualTo(Integer value) {
			addCriterion("STATE_CD <>", value, "stateCd");
			return (Criteria) this;
		}

		public Criteria andStateCdGreaterThan(Integer value) {
			addCriterion("STATE_CD >", value, "stateCd");
			return (Criteria) this;
		}

		public Criteria andStateCdGreaterThanOrEqualTo(Integer value) {
			addCriterion("STATE_CD >=", value, "stateCd");
			return (Criteria) this;
		}

		public Criteria andStateCdLessThan(Integer value) {
			addCriterion("STATE_CD <", value, "stateCd");
			return (Criteria) this;
		}

		public Criteria andStateCdLessThanOrEqualTo(Integer value) {
			addCriterion("STATE_CD <=", value, "stateCd");
			return (Criteria) this;
		}

		public Criteria andStateCdIn(List<Integer> values) {
			addCriterion("STATE_CD in", values, "stateCd");
			return (Criteria) this;
		}

		public Criteria andStateCdNotIn(List<Integer> values) {
			addCriterion("STATE_CD not in", values, "stateCd");
			return (Criteria) this;
		}

		public Criteria andStateCdBetween(Integer value1, Integer value2) {
			addCriterion("STATE_CD between", value1, value2, "stateCd");
			return (Criteria) this;
		}

		public Criteria andStateCdNotBetween(Integer value1, Integer value2) {
			addCriterion("STATE_CD not between", value1, value2, "stateCd");
			return (Criteria) this;
		}

		public Criteria andCountyCdIsNull() {
			addCriterion("COUNTY_CD is null");
			return (Criteria) this;
		}

		public Criteria andCountyCdIsNotNull() {
			addCriterion("COUNTY_CD is not null");
			return (Criteria) this;
		}

		public Criteria andCountyCdEqualTo(Integer value) {
			addCriterion("COUNTY_CD =", value, "countyCd");
			return (Criteria) this;
		}

		public Criteria andCountyCdNotEqualTo(Integer value) {
			addCriterion("COUNTY_CD <>", value, "countyCd");
			return (Criteria) this;
		}

		public Criteria andCountyCdGreaterThan(Integer value) {
			addCriterion("COUNTY_CD >", value, "countyCd");
			return (Criteria) this;
		}

		public Criteria andCountyCdGreaterThanOrEqualTo(Integer value) {
			addCriterion("COUNTY_CD >=", value, "countyCd");
			return (Criteria) this;
		}

		public Criteria andCountyCdLessThan(Integer value) {
			addCriterion("COUNTY_CD <", value, "countyCd");
			return (Criteria) this;
		}

		public Criteria andCountyCdLessThanOrEqualTo(Integer value) {
			addCriterion("COUNTY_CD <=", value, "countyCd");
			return (Criteria) this;
		}

		public Criteria andCountyCdIn(List<Integer> values) {
			addCriterion("COUNTY_CD in", values, "countyCd");
			return (Criteria) this;
		}

		public Criteria andCountyCdNotIn(List<Integer> values) {
			addCriterion("COUNTY_CD not in", values, "countyCd");
			return (Criteria) this;
		}

		public Criteria andCountyCdBetween(Integer value1, Integer value2) {
			addCriterion("COUNTY_CD between", value1, value2, "countyCd");
			return (Criteria) this;
		}

		public Criteria andCountyCdNotBetween(Integer value1, Integer value2) {
			addCriterion("COUNTY_CD not between", value1, value2, "countyCd");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNull() {
			addCriterion("UPDATE_DATE is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNotNull() {
			addCriterion("UPDATE_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateEqualTo(Date value) {
			addCriterion("UPDATE_DATE =", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotEqualTo(Date value) {
			addCriterion("UPDATE_DATE <>", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThan(Date value) {
			addCriterion("UPDATE_DATE >", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("UPDATE_DATE >=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThan(Date value) {
			addCriterion("UPDATE_DATE <", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
			addCriterion("UPDATE_DATE <=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIn(List<Date> values) {
			addCriterion("UPDATE_DATE in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotIn(List<Date> values) {
			addCriterion("UPDATE_DATE not in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateBetween(Date value1, Date value2) {
			addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
			addCriterion("UPDATE_DATE not between", value1, value2,
					"updateDate");
			return (Criteria) this;
		}

		public Criteria andAltUnitsIsNull() {
			addCriterion("ALT_UNITS is null");
			return (Criteria) this;
		}

		public Criteria andAltUnitsIsNotNull() {
			addCriterion("ALT_UNITS is not null");
			return (Criteria) this;
		}

		public Criteria andAltUnitsEqualTo(Integer value) {
			addCriterion("ALT_UNITS =", value, "altUnits");
			return (Criteria) this;
		}

		public Criteria andAltUnitsNotEqualTo(Integer value) {
			addCriterion("ALT_UNITS <>", value, "altUnits");
			return (Criteria) this;
		}

		public Criteria andAltUnitsGreaterThan(Integer value) {
			addCriterion("ALT_UNITS >", value, "altUnits");
			return (Criteria) this;
		}

		public Criteria andAltUnitsGreaterThanOrEqualTo(Integer value) {
			addCriterion("ALT_UNITS >=", value, "altUnits");
			return (Criteria) this;
		}

		public Criteria andAltUnitsLessThan(Integer value) {
			addCriterion("ALT_UNITS <", value, "altUnits");
			return (Criteria) this;
		}

		public Criteria andAltUnitsLessThanOrEqualTo(Integer value) {
			addCriterion("ALT_UNITS <=", value, "altUnits");
			return (Criteria) this;
		}

		public Criteria andAltUnitsIn(List<Integer> values) {
			addCriterion("ALT_UNITS in", values, "altUnits");
			return (Criteria) this;
		}

		public Criteria andAltUnitsNotIn(List<Integer> values) {
			addCriterion("ALT_UNITS not in", values, "altUnits");
			return (Criteria) this;
		}

		public Criteria andAltUnitsBetween(Integer value1, Integer value2) {
			addCriterion("ALT_UNITS between", value1, value2, "altUnits");
			return (Criteria) this;
		}

		public Criteria andAltUnitsNotBetween(Integer value1, Integer value2) {
			addCriterion("ALT_UNITS not between", value1, value2, "altUnits");
			return (Criteria) this;
		}

		public Criteria andLocalAquiferCdIsNull() {
			addCriterion("LOCAL_AQUIFER_CD is null");
			return (Criteria) this;
		}

		public Criteria andLocalAquiferCdIsNotNull() {
			addCriterion("LOCAL_AQUIFER_CD is not null");
			return (Criteria) this;
		}

		public Criteria andLocalAquiferCdEqualTo(String value) {
			addCriterion("LOCAL_AQUIFER_CD =", value, "localAquiferCd");
			return (Criteria) this;
		}

		public Criteria andLocalAquiferCdNotEqualTo(String value) {
			addCriterion("LOCAL_AQUIFER_CD <>", value, "localAquiferCd");
			return (Criteria) this;
		}

		public Criteria andLocalAquiferCdGreaterThan(String value) {
			addCriterion("LOCAL_AQUIFER_CD >", value, "localAquiferCd");
			return (Criteria) this;
		}

		public Criteria andLocalAquiferCdGreaterThanOrEqualTo(String value) {
			addCriterion("LOCAL_AQUIFER_CD >=", value, "localAquiferCd");
			return (Criteria) this;
		}

		public Criteria andLocalAquiferCdLessThan(String value) {
			addCriterion("LOCAL_AQUIFER_CD <", value, "localAquiferCd");
			return (Criteria) this;
		}

		public Criteria andLocalAquiferCdLessThanOrEqualTo(String value) {
			addCriterion("LOCAL_AQUIFER_CD <=", value, "localAquiferCd");
			return (Criteria) this;
		}

		public Criteria andLocalAquiferCdLike(String value) {
			addCriterion("LOCAL_AQUIFER_CD like", value, "localAquiferCd");
			return (Criteria) this;
		}

		public Criteria andLocalAquiferCdNotLike(String value) {
			addCriterion("LOCAL_AQUIFER_CD not like", value, "localAquiferCd");
			return (Criteria) this;
		}

		public Criteria andLocalAquiferCdIn(List<String> values) {
			addCriterion("LOCAL_AQUIFER_CD in", values, "localAquiferCd");
			return (Criteria) this;
		}

		public Criteria andLocalAquiferCdNotIn(List<String> values) {
			addCriterion("LOCAL_AQUIFER_CD not in", values, "localAquiferCd");
			return (Criteria) this;
		}

		public Criteria andLocalAquiferCdBetween(String value1, String value2) {
			addCriterion("LOCAL_AQUIFER_CD between", value1, value2,
					"localAquiferCd");
			return (Criteria) this;
		}

		public Criteria andLocalAquiferCdNotBetween(String value1, String value2) {
			addCriterion("LOCAL_AQUIFER_CD not between", value1, value2,
					"localAquiferCd");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table GW_DATA_PORTAL.WELL_REGISTRY
	 * @mbggenerated  Wed Apr 11 16:58:46 CDT 2012
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table GW_DATA_PORTAL.WELL_REGISTRY
     *
     * @mbggenerated do_not_delete_during_merge Tue Mar 27 15:44:16 CDT 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}