package gov.usgs.ngwmn.dm.dao;

import gov.usgs.ngwmn.dm.dao.WellRegistry;
import gov.usgs.ngwmn.dm.dao.WellRegistryExample;
import java.util.List;

public interface WellRegistryDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.WELL_REGISTRY
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	int countByExample(WellRegistryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GW_DATA_PORTAL.WELL_REGISTRY
	 * @mbggenerated  Tue Mar 27 16:54:20 CDT 2012
	 */
	List<WellRegistry> selectByExample(WellRegistryExample example);

	WellRegistry findByKey(String agencyID, String wellID);

	List<WellRegistry> selectAll();
}
